In [1]:
import pandas as pd
import numpy as np

RawData=pd.read_csv('/Users/kurakulaenus/Desktop/A - Python/C - Projects/B - OriginalData/VGProject-main/VideoGamesSales.csv',encoding='latin1')
RawData

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
0,1,Wii Sports,Wii,2010,Jan,Sports,Nintendo,United States,Fairfield,California,West,$41.49,82.74,12.447,24.822
1,2,Super Mario Bros.,NES,2010,Feb,Platform,Nintendo,United States,Edmonds,Washington,West,$29.08,40.24,8.724,12.072
2,3,Mario Kart Wii,Wii,2010,Mar,Racing,Nintendo,United States,Louisville,Kentucky,South,$15.85,35.82,4.755,10.746
3,4,Wii Sports Resort,Wii,2010,Apr,Sports,Nintendo,United States,Round Rock,Texas,Central,$15.75,33.00,4.725,9.900
4,5,Pokemon Red/Pokemon Blue,GB,2010,May,Role-Playing,Nintendo,United States,Nashville,Tennessee,South,$11.27,31.37,3.381,9.411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5904,5890,Crazy Taxi: Catch a Ride,GBA,2017,Sep,Racing,THQ,Australia,Sydney,New South Wales,West,0.21,0.30,0.063,0.090
5905,5891,MySims Party,DS,2017,Oct,Simulation,Electronic Arts,Australia,Sydney,New South Wales,West,0.15,0.30,0.045,0.090
5906,5892,Harry Potter and the Order of the Phoenix,X360,2017,Nov,Action,Electronic Arts,Australia,Sydney,New South Wales,West,0.24,0.30,0.072,0.090
5907,5893,Skylanders: SuperChargers,PS4,2017,Dec,Action,Activision,Australia,Sydney,New South Wales,West,0.17,0.30,0.051,0.090
5908,5894,Macross Digital Mission VF-X,PS,2017,Jan,Simulation,Namco Bandai Games,Australia,Sydney,New South Wales,West,0,0.30,0.000,0.090

In [2]:
df=RawData.copy()
df

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
0,1,Wii Sports,Wii,2010,Jan,Sports,Nintendo,United States,Fairfield,California,West,$41.49,82.74,12.447,24.822
1,2,Super Mario Bros.,NES,2010,Feb,Platform,Nintendo,United States,Edmonds,Washington,West,$29.08,40.24,8.724,12.072
2,3,Mario Kart Wii,Wii,2010,Mar,Racing,Nintendo,United States,Louisville,Kentucky,South,$15.85,35.82,4.755,10.746
3,4,Wii Sports Resort,Wii,2010,Apr,Sports,Nintendo,United States,Round Rock,Texas,Central,$15.75,33.00,4.725,9.900
4,5,Pokemon Red/Pokemon Blue,GB,2010,May,Role-Playing,Nintendo,United States,Nashville,Tennessee,South,$11.27,31.37,3.381,9.411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5904,5890,Crazy Taxi: Catch a Ride,GBA,2017,Sep,Racing,THQ,Australia,Sydney,New South Wales,West,0.21,0.30,0.063,0.090
5905,5891,MySims Party,DS,2017,Oct,Simulation,Electronic Arts,Australia,Sydney,New South Wales,West,0.15,0.30,0.045,0.090
5906,5892,Harry Potter and the Order of the Phoenix,X360,2017,Nov,Action,Electronic Arts,Australia,Sydney,New South Wales,West,0.24,0.30,0.072,0.090
5907,5893,Skylanders: SuperChargers,PS4,2017,Dec,Action,Activision,Australia,Sydney,New South Wales,West,0.17,0.30,0.051,0.090
5908,5894,Macross Digital Mission VF-X,PS,2017,Jan,Simulation,Namco Bandai Games,Australia,Sydney,New South Wales,West,0,0.30,0.000,0.090

# Exploratory Data Analysis

In [3]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Month', 'Genre', 'Publisher',
       'Country', 'City', 'State', 'Region', 'NA_Sales', 'Global_Sales',
       'NA_Profit', 'Global_Profit'],
      dtype='object')

In [4]:
df.index

RangeIndex(start=0, stop=5909, step=1)

In [5]:
df.shape

(5909, 15)

In [6]:
df.dtypes

Rank               int64
Name              object
Platform          object
Year               int64
Month             object
Genre             object
Publisher         object
Country           object
City              object
State             object
Region            object
NA_Sales          object
Global_Sales     float64
NA_Profit        float64
Global_Profit    float64
dtype: object

In [7]:
df.head(5)

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
0,1,Wii Sports,Wii,2010,Jan,Sports,Nintendo,United States,Fairfield,California,West,$41.49,82.74,12.447,24.822
1,2,Super Mario Bros.,NES,2010,Feb,Platform,Nintendo,United States,Edmonds,Washington,West,$29.08,40.24,8.724,12.072
2,3,Mario Kart Wii,Wii,2010,Mar,Racing,Nintendo,United States,Louisville,Kentucky,South,$15.85,35.82,4.755,10.746
3,4,Wii Sports Resort,Wii,2010,Apr,Sports,Nintendo,United States,Round Rock,Texas,Central,$15.75,33.00,4.725,9.900
4,5,Pokemon Red/Pokemon Blue,GB,2010,May,Role-Playing,Nintendo,United States,Nashville,Tennessee,South,$11.27,31.37,3.381,9.411

In [8]:
df.tail(5)

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
5904,5890,Crazy Taxi: Catch a Ride,GBA,2017,Sep,Racing,THQ,Australia,Sydney,New South Wales,West,0.21,0.3,0.063,0.09
5905,5891,MySims Party,DS,2017,Oct,Simulation,Electronic Arts,Australia,Sydney,New South Wales,West,0.15,0.3,0.045,0.09
5906,5892,Harry Potter and the Order of the Phoenix,X360,2017,Nov,Action,Electronic Arts,Australia,Sydney,New South Wales,West,0.24,0.3,0.072,0.09
5907,5893,Skylanders: SuperChargers,PS4,2017,Dec,Action,Activision,Australia,Sydney,New South Wales,West,0.17,0.3,0.051,0.09
5908,5894,Macross Digital Mission VF-X,PS,2017,Jan,Simulation,Namco Bandai Games,Australia,Sydney,New South Wales,West,0,0.3,0.000,0.09

In [9]:
df.sample(5)

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
1703,1692,Pro Evolution Soccer 2008,Wii,2011,Nov,Sports,Konami Digital Entertainment,United States,New York City,New York,East,0.09,1.19,0.027,0.357
1627,1619,Farming Simulator 2015,PC,2015,Oct,Simulation,Focus Home Interactive,United States,Oklahoma City,Oklahoma,Central,0.08,1.23,0.024,0.369
2203,2192,Army of Two: The 40th Day,X360,2012,Jul,Shooter,Electronic Arts,United States,Newport News,Virginia,South,0.62,0.95,0.186,0.285
5313,5302,Hannah Montana: The Movie,Wii,2016,Sep,Adventure,Disney Interactive Studios,Australia,Sydney,New South Wales,West,0.13,0.35,0.039,0.105
5535,5524,"Warhammer 40,000: Squad Command",PSP,2017,Mar,Strategy,THQ,Australia,Sydney,New South Wales,West,0.11,0.33,0.033,0.099

In [10]:
df.nunique()

Rank             5893
Name             4139
Platform           26
Year                8
Month              14
Genre              12
Publisher         219
Country             3
City              391
State              56
Region              6
NA_Sales          420
Global_Sales      594
NA_Profit         409
Global_Profit     594
dtype: int64

In [11]:
df.value_counts()

Rank  Name                                                 Platform  Year  Month  Genre       Publisher                    Country        City       State            Region  NA_Sales  Global_Sales  NA_Profit  Global_Profit
9     New Super Mario Bros. Wii                            Wii       2010  Sep    Platform    Nintendo                     USA            Fairfield  Ohio             East    $14.59    28.62         4.377      8.586            5
373   Donkey Kong Country 3: Dixie Kong's Double Trouble!  SNES      2010  Jan    Platform    Nintendo                     United States  Lancaster  Ohio             East    1.17      3.51          0.351      1.053            4
60    Super Mario 64                                       DS        2010  Dec    Platform    Nintendo                     United States  Seattle    Washington       West    5.08      10.42         1.524      3.126            4
5876  Dynasty Warriors 6                                   X360      2017  Jul    Action      Tecmo Koei                   Australia      Sydney     New South Wales  West    0.15      0.30          0.045      0.090            4
1649  WCW Mayhem                                           PS        2015  Apr    Fighting    Electronic Arts              United States  Akron      Ohio             East    0.68      1.22          0.204      0.366            4
                                                                                                                                                                                                                                 ..
1965  Apollo Justice: Ace Attorney                         DS        2012  Aug    Adventure   Capcom                       United States  Vancouver  Washington       West    0.32      1.06          0.096      0.318            1
1964  Warhawk                                              PS3       2012  Jul    Simulation  Sony Computer Entertainment  United States  Pasadena   California       West    0.49      1.06          0.147      0.318            1
1963  Seek and Destroy                                     PS2       2012  Jun    Racing      Play It                      United States  Pasadena   California       West    0.52      1.06          0.156      0.318            1
1962  Virtua Tennis 3                                      PS3       2012  May    Sports      Sega                         United States  Torrance   California       West    0.23      1.06          0.069      0.318            1
5894  Macross Digital Mission VF-X                         PS        2017  Jan    Simulation  Namco Bandai Games           Australia      Sydney     New South Wales  West    0         0.30          0.000      0.090            1
Name: count, Length: 5854, dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5909 entries, 0 to 5908
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           5909 non-null   int64
 1   Name           5909 non-null   object
 2   Platform       5909 non-null   object
 3   Year           5909 non-null   int64
 4   Month          5909 non-null   object
 5   Genre          5909 non-null   object
 6   Publisher      5897 non-null   object
 7   Country        5909 non-null   object
 8   City           5909 non-null   object
 9   State          5909 non-null   object
 10  Region         5882 non-null   object
 11  NA_Sales       5909 non-null   object
 12  Global_Sales   5909 non-null   float64
 13  NA_Profit      5909 non-null   float64
 14  Global_Profit  5909 non-null   float64
dtypes: float64(3), int64(2), object(10)
memory usage: 692.6+ KB

In [13]:
df.describe()

              Rank         Year  Global_Sales    NA_Profit  Global_Profit
count  5909.000000  5909.000000   5909.000000  5909.000000    5909.000000
mean   2943.953461  2013.197834      1.344519     0.198809       0.403356
std    1704.649477     2.223609      2.526125     0.400008       0.757837
min       1.000000  2010.000000      0.300000     0.000000       0.090000
25%    1469.000000  2011.000000      0.440000     0.060000       0.132000
50%    2943.000000  2013.000000      0.690000     0.108000       0.207000
75%    4420.000000  2015.000000      1.330000     0.204000       0.399000
max    5894.000000  2017.000000     82.740000    12.447000      24.822000

# RESTART

In [14]:
df=RawData.copy()
df

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
0,1,Wii Sports,Wii,2010,Jan,Sports,Nintendo,United States,Fairfield,California,West,$41.49,82.74,12.447,24.822
1,2,Super Mario Bros.,NES,2010,Feb,Platform,Nintendo,United States,Edmonds,Washington,West,$29.08,40.24,8.724,12.072
2,3,Mario Kart Wii,Wii,2010,Mar,Racing,Nintendo,United States,Louisville,Kentucky,South,$15.85,35.82,4.755,10.746
3,4,Wii Sports Resort,Wii,2010,Apr,Sports,Nintendo,United States,Round Rock,Texas,Central,$15.75,33.00,4.725,9.900
4,5,Pokemon Red/Pokemon Blue,GB,2010,May,Role-Playing,Nintendo,United States,Nashville,Tennessee,South,$11.27,31.37,3.381,9.411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5904,5890,Crazy Taxi: Catch a Ride,GBA,2017,Sep,Racing,THQ,Australia,Sydney,New South Wales,West,0.21,0.30,0.063,0.090
5905,5891,MySims Party,DS,2017,Oct,Simulation,Electronic Arts,Australia,Sydney,New South Wales,West,0.15,0.30,0.045,0.090
5906,5892,Harry Potter and the Order of the Phoenix,X360,2017,Nov,Action,Electronic Arts,Australia,Sydney,New South Wales,West,0.24,0.30,0.072,0.090
5907,5893,Skylanders: SuperChargers,PS4,2017,Dec,Action,Activision,Australia,Sydney,New South Wales,West,0.17,0.30,0.051,0.090
5908,5894,Macross Digital Mission VF-X,PS,2017,Jan,Simulation,Namco Bandai Games,Australia,Sydney,New South Wales,West,0,0.30,0.000,0.090

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5909 entries, 0 to 5908
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           5909 non-null   int64
 1   Name           5909 non-null   object
 2   Platform       5909 non-null   object
 3   Year           5909 non-null   int64
 4   Month          5909 non-null   object
 5   Genre          5909 non-null   object
 6   Publisher      5897 non-null   object
 7   Country        5909 non-null   object
 8   City           5909 non-null   object
 9   State          5909 non-null   object
 10  Region         5882 non-null   object
 11  NA_Sales       5909 non-null   object
 12  Global_Sales   5909 non-null   float64
 13  NA_Profit      5909 non-null   float64
 14  Global_Profit  5909 non-null   float64
dtypes: float64(3), int64(2), object(10)
memory usage: 692.6+ KB

# check and drop_duplicates

In [16]:
df.duplicated().sum()

np.int64(16)

In [17]:
df[df.duplicated()]

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
9,9,New Super Mario Bros. Wii,Wii,2010,Sep,Platform,Nintendo,USA,Fairfield,Ohio,East,$14.59,28.62,4.377,8.586
10,9,New Super Mario Bros. Wii,Wii,2010,Sep,Platform,Nintendo,USA,Fairfield,Ohio,East,$14.59,28.62,4.377,8.586
11,9,New Super Mario Bros. Wii,Wii,2010,Sep,Platform,Nintendo,USA,Fairfield,Ohio,East,$14.59,28.62,4.377,8.586
12,9,New Super Mario Bros. Wii,Wii,2010,Sep,Platform,Nintendo,USA,Fairfield,Ohio,East,$14.59,28.62,4.377,8.586
64,60,Super Mario 64,DS,2010,Dec,Platform,Nintendo,United States,Seattle,Washington,West,5.08,10.42,1.524,3.126
65,60,Super Mario 64,DS,2010,Dec,Platform,Nintendo,United States,Seattle,Washington,West,5.08,10.42,1.524,3.126
66,60,Super Mario 64,DS,2010,Dec,Platform,Nintendo,United States,Seattle,Washington,West,5.08,10.42,1.524,3.126
380,373,Donkey Kong Country 3: Dixie Kong's Double Tro...,SNES,2010,Jan,Platform,Nintendo,United States,Lancaster,Ohio,East,1.17,3.51,0.351,1.053
381,373,Donkey Kong Country 3: Dixie Kong's Double Tro...,SNES,2010,Jan,Platform,Nintendo,United States,Lancaster,Ohio,East,1.17,3.51,0.351,1.053
382,373,Donkey Kong Country 3: Dixie Kong's Double Tro...,SNES,2010,Jan,Platform,Nintendo,United States,Lancaster,Ohio,East,1.17,3.51,0.351,1.053
1658,1649,WCW Mayhem,PS,2015,Apr,Fighting,Electronic Arts,United States,Akron,Ohio,East,0.68,1.22,0.204,0.366
1659,1649,WCW Mayhem,PS,2015,Apr,Fighting,Electronic Arts,United States,Akron,Ohio,East,0.68,1.22,0.204,0.366
1660,1649,WCW Mayhem,PS,2015,Apr,Fighting,Electronic Arts,United States,Akron,Ohio,East,0.68,1.22,0.204,0.366
5888,5876,Dynasty Warriors 6,X360,2017,Jul,Action,Tecmo Koei,Australia,Sydney,New South Wales,West,0.15,0.30,0.045,0.090
5889,5876,Dynasty Warriors 6,X360,2017,Jul,Action,Tecmo Koei,Australia,Sydney,New South Wales,West,0.15,0.30,0.045,0.090
5890,5876,Dynasty Warriors 6,X360,2017,Jul,Action,Tecmo Koei,Australia,Sydney,New South Wales,West,0.15,0.30,0.045,0.090

In [18]:
df.shape

(5909, 15)

In [19]:
# Count duplicates per column
for col in df.columns:
    print(col, df[col].duplicated().sum())

Rank 16
Name 1770
Platform 5883
Year 5901
Month 5895
Genre 5897
Publisher 5689
Country 5906
City 5518
State 5853
Region 5902
NA_Sales 5489
Global_Sales 5315
NA_Profit 5500
Global_Profit 5315

In [20]:
# If we have duplicates then give all columns to drop them
df.drop_duplicates(inplace=True)  
df.duplicated().sum()

np.int64(0)

In [21]:
pd.set_option('display.max_rows',None)
df[df['Name'].duplicated()]

      Rank                                               Name Platform  Year  \
27      24                                 Grand Theft Auto V     X360  2010
39      36                         Call of Duty: Black Ops II     X360  2010
41      38                     Call of Duty: Modern Warfare 3      PS3  2010
44      41                            Call of Duty: Black Ops      PS3  2010
48      45                                 Grand Theft Auto V      PS4  2010
59      56                     Call of Duty: Modern Warfare 2      PS3  2010
60      57                                Grand Theft Auto IV      PS3  2010
63      60                                     Super Mario 64       DS  2010
74      68                               Call of Duty: Ghosts      PS3  2010
108    102                          Call of Duty: Black Ops 3     XOne  2010
110    104                                      Battlefield 3      PS3  2010
127    121                     Call of Duty 4: Modern Warfare      PS3  2010
133    127                        The Elder Scrolls V: Skyrim      PS3  2010
141    135                                Red Dead Redemption     X360  2010
162    156                                             Tetris      NES  2010
171    165                                  Super Mario World      GBA  2010
173    167                         Call of Duty: World at War      PS3  2010
175    169                                          Minecraft      PS3  2010
179    173                               Assassin's Creed III     X360  2010
183    177                                Assassin's Creed II     X360  2010
189    183                                Super Mario Bros. 3      GBA  2010
192    186                                     FIFA Soccer 13     X360  2010
196    190                 Mario & Sonic at the Olympic Games       DS  2010
200    194                     Call of Duty: Advanced Warfare     XOne  2010
204    198                                 Grand Theft Auto V     XOne  2010
207    201                                  Super Mario Bros.       GB  2010
210    204                Super Smash Bros. for Wii U and 3DS     WiiU  2010
219    213                  LEGO Star Wars: The Complete Saga       DS  2010
222    216                                          Dr. Mario      NES  2010
225    219                                   Assassin's Creed      PS3  2010
226    220                                            FIFA 15      PS3  2010
229    223                                Batman: Arkham City     X360  2010
237    231                   Guitar Hero III: Legends of Rock      Wii  2010
243    237                                     The Last of Us      PS4  2010
244    238                   Guitar Hero III: Legends of Rock     X360  2010
251    245                     Call of Duty: Advanced Warfare      PS3  2010
263    257                                            FIFA 14     X360  2010
264    258                     Call of Duty: Advanced Warfare     X360  2010
275    269               The Legend of Zelda: Ocarina of Time      3DS  2010
280    274                      Assassin's Creed: Revelations     X360  2010
282    276                                            FIFA 12     X360  2010
294    288                                          Fallout 4     XOne  2010
304    298                                          Minecraft      PS4  2010
306    300                                          Fallout 3      PS3  2010
317    311                        The Elder Scrolls V: Skyrim       PC  2010
356    350                               Call of Duty: Ghosts      PS4  2010
367    361             Grand Theft Auto: Liberty City Stories      PS2  2010
372    366                                      Battlefield 4     X360  2010
373    367                                     FIFA Soccer 11     X360  2010
377    371          Mario & Sonic at the Olympic Winter Games       DS  2010
378    372                                    Resident Evil 5     X360  2010
385    376                              Batman: Arkham Asylum     X360  2010
388    379                       Star Wars Battlefront (2015)     XOne  2010
391    382                            Assassin's Creed: Unity     XOne  2010
396    387                                      Battlefield 4      PS4  2010
411    402                    Assassin's Creed IV: Black Flag     X360  2010
420    411                                            Destiny     XOne  2010
426    417                                            FIFA 16     XOne  2010
440    431                                 Fallout: New Vegas      PS3  2010
441    432                         LEGO Batman: The Videogame      Wii  2010
446    437                         LEGO Batman: The Videogame       DS  2010
455    446                     The Elder Scrolls IV: Oblivion      PS3  2010
459    450                                            FIFA 15     X360  2010
469    460                                          Far Cry 3     X360  2010
487    478                         Battlefield: Bad Company 2      PS3  2010
493    484                                  Street Fighter IV     X360  2010
502    493                Super Mario World 2: Yoshi's Island      GBA  2010
503    494                                            FIFA 14      PS4  2010
508    499                        Need for Speed: Most Wanted      PS3  2010
515    506                               Call of Duty: Ghosts     XOne  2010
523    514                                            FIFA 16      PS3  2010
524    515                      Assassin's Creed: Brotherhood      PS3  2010
543    534                                      Battlefield 3       PC  2010
556    547                    Assassin's Creed IV: Black Flag      PS4  2010
559    550                                         L.A. Noire     X360  2010
561    552            The Legend of Zelda: A Link to the Past      GBA  2010
574    565                                      Mortal Kombat      GEN  2010
576    567                            Guitar Hero: World Tour     X360  2010
577    568                                     Medal of Honor       PS  2010
580    571                         Tom Clancy's Splinter Cell      PS2  2010
585    576                  LEGO Star Wars: The Complete Saga     X360  2010
592    583                                     Medal of Honor     X360  2010
593    584                                     FIFA Soccer 10     X360  2010
602    593                                    LittleBigPlanet      PSP  2010
613    604                                      Madden NFL 13      PS3  2010
626    617                              Saints Row: The Third      PS3  2010
633    624                                           NBA 2K13      PS3  2010
653    644                                          Minecraft     XOne  2010
655    646                                      Madden NFL 16     XOne  2010
661    652                                      Zumba Fitness     X360  2010
662    653        LEGO Indiana Jones: The Original Adventures      Wii  2010
667    659                  LEGO Star Wars: The Complete Saga      PS3  2010
672    664                                      Madden NFL 11      PS3  2010
674    666                                      Madden NFL 08     X360  2010
678    670                                      Madden NFL 10      PS3  2010
681    673                       LEGO Harry Potter: Years 1-4       DS  2010
684    676                         Midnight Club: Los Angeles     X360  2010
689    681                                         The Sims 3     X360  2010
691    683                                           NBA 2K16     XOne  2010
703    695                                        Dead Island      PS3  2010
704    696                                     Tomb Raider II       PC  2010
706    698                       Need for Speed Underground 2       XB  2011
711    703                                     FIFA Soccer 09      PS2  2011
712    704                     Star Wars: The Force Unleashed      PS3  2011
713    705                                      Borderlands 2      PS3  2011
720    712                   Guitar Hero III: Legends of Rock      PS3  2011
721    713                                     Call of Duty 3      Wii  2011
722    714                                    Resident Evil 4      Wii  2011
723    715                                          Minecraft      PSV  2011
727    719                                      Madden NFL 12      PS3  2011
728    720                                 Monster Hunter Tri      Wii  2011
733    725        LEGO Indiana Jones: The Original Adventures       DS  2011
739    731                        Need for Speed: Hot Pursuit     X360  2011
741    733                    Assassin's Creed IV: Black Flag     XOne  2011
744    736                                            Frogger     2600  2011
745    737                                     Guitar Hero II     X360  2011
754    746                                Donkey Kong Country       GB  2011
762    754                                 Final Fantasy XIII     X360  2011
770    762                                            FIFA 15     XOne  2011
782    774                                  Final Fantasy III       DS  2011
785    777                                               Golf       GB  2011
786    778                                           NBA 2K12      PS3  2011
787    779                                        Borderlands      PS3  2011
788    780                             Tony Hawk's Pro Skater      N64  2011
789    781                     PES 2009: Pro Evolution Soccer      PS3  2011
792    784                                          Rock Band      Wii  2011
794    786                                      Mortal Kombat     X360  2011
803    795                                       Finding Nemo      PS2  2011
814    806          Ghostbusters: The Video Game (DS Version)      PS3  2011
817    809                                            Skate 3      PS3  2011
823    815                          Need for Speed: ProStreet     X360  2011
824    816                                         The Sims 3      PS3  2011
827    819                                    The Incredibles      GBA  2011
831    823                          Need for Speed: ProStreet      PS3  2011
832    824                                     Carnival Games       DS  2011
833    825                                           NBA 2K14      PS3  2011
836    828                                         Diablo III      PS3  2011
844    836                                Donkey Kong Country      GBA  2011
848    840                                       Just Dance 3     X360  2011
852    844                                      Madden NFL 15     X360  2011
855    847                          Tom Clancy's The Division     XOne  2011
856    848                           LEGO Marvel Super Heroes      PS3  2011
862    854                                             Tennis       GB  2011
863    855            Harry Potter and the Chamber of Secrets      GBA  2011
864    856            Harry Potter and the Chamber of Secrets       PS  2011
866    858                                      Battlefield 4     XOne  2011
867    859                                    Resident Evil 6     X360  2011
871    863                         Call of Duty: World at War      Wii  2011
881    873                                            Destiny     X360  2011
883    875                      Grand Theft Auto: San Andreas       XB  2011
887    879                                     FIFA Soccer 09     X360  2011
895    887                             Batman: Arkham Origins     X360  2011
896    888                            Guitar Hero: World Tour      PS3  2011
900    892                      Mortal Kombat vs. DC Universe     X360  2011
901    893                                         Watch Dogs      PS3  2011
903    895                                 Tomb Raider (2013)     X360  2011
905    897                              Need for Speed: Shift     X360  2011
906    898                                           Monopoly      Wii  2011
913    905                     Star Wars: The Force Unleashed      Wii  2011
920    912                                      Madden NFL 09      PS3  2011
932    924                        Donkey Kong Country Returns      3DS  2011
934    926                                      Madden NFL 06       XB  2011
963    955                                       Namco Museum      PS2  2011
969    961                                         Crazy Taxi       DC  2011
972    964                            Guitar Hero: World Tour      PS2  2011
974    966                                      Madden NFL 07     X360  2011
975    967                                           NBA 2K11      PS3  2011
977    969                          Call of Duty: Black Ops 3      PS3  2011
988    980                The Legend of Zelda: The Wind Waker     WiiU  2011
990    982                      High School Musical: Sing It!      Wii  2011
992    984                                      Madden NFL 25      PS3  2011
996    988                                UFC 2009 Undisputed      PS3  2011
1004   996                           Tom Clancy's Ghost Recon       XB  2011
1006   998                                  BioShock Infinite      PS3  2011
1007   999                                 Hitman: Absolution     X360  2011
1009  1001                          Call of Duty: Black Ops 3     X360  2011
1011  1003                                     FIFA Soccer 08      PS3  2011
1014  1006                                     Kingdom Hearts      PS3  2011
1015  1007                             Star Wars: Battlefront       XB  2011
1026  1018                                           Portal 2      PS3  2011
1032  1024                                         Diablo III      PS4  2011
1034  1026                                            Destiny      PS3  2011
1038  1030              Harry Potter and the Sorcerer's Stone       GB  2011
1042  1034  Rockstar Games Double Pack: Grand Theft Auto I...      PS2  2011
1047  1039                     Call of Duty: Modern Warfare 3       PC  2011
1048  1040                                    Madden NFL 2005       XB  2011
1055  1047                         Need for Speed Underground       XB  2011
1057  1049                                      Tetris Worlds      GBA  2011
1060  1052                                     FIFA Soccer 10      PS2  2011
1068  1060                                           NBA 2K15     XOne  2011
1069  1061                                       Saints Row 2      PS3  2011
1072  1064                                Dragon Age: Origins      PS3  2011
1073  1065                                            FIFA 16     X360  2011
1076  1068              Harry Potter and the Sorcerer's Stone      GBA  2011
1077  1069                         Need For Speed: Undercover     X360  2011
1080  1072                                    Resident Evil 4       GC  2011
1090  1082                                             MySims      Wii  2011
1098  1090                          Star Wars: Battlefront II       XB  2011
1100  1092                           Tony Hawk's Pro Skater 3       PS  2011
1111  1103                                        Max Payne 3     X360  2011
1120  1112                 Dragon Quest V: Tenkuu no Hanayome      PS2  2011
1133  1125                                       ESPN NFL 2K5       XB  2012
1136  1128                            Call of Duty: Black Ops       PC  2012
1140  1132                                           NBA 2K15     X360  2012
1142  1134                                       Just Cause 2     X360  2012
1143  1135                                          Rock Band      PS3  2012
1152  1144                                           Baseball       GB  2012
1157  1149                                          Far Cry 4     XOne  2012
1167  1159                                       Sonic Heroes       GC  2012
1170  1162             The Legend of Zelda: Twilight Princess       GC  2012
1173  1165                                        Mario Bros.     2600  2012
1174  1166                          Pro Evolution Soccer 2008      PS3  2012
1176  1168                       LEGO Harry Potter: Years 1-4     X360  2012
1183  1175                        Need for Speed: Most Wanted     X360  2012
1190  1182                          Pro Evolution Soccer 2010      PS2  2012
1196  1188                                Fight Night Round 3      PS2  2012
1203  1195                           LEGO Marvel Super Heroes      PS4  2012
1205  1197                                         Dishonored      PS3  2012
1209  1201                                         BioShock 2      PS3  2012
1212  1204                                         Watch Dogs     XOne  2012
1227  1219                         Call of Duty: Black Ops II       PC  2012
1229  1221                                     MySims Kingdom      Wii  2012
1234  1226                                            FIFA 17     XOne  2012
1247  1239                                           Mafia II      PS3  2012
1248  1240                                     Call of Duty 3      PS3  2012
1251  1243                                      Madden NFL 15     XOne  2012
1253  1245                 LEGO Star Wars III: The Clone Wars     X360  2012
1259  1251                                  The Simpsons Game      PS2  2012
1260  1252                                           Monopoly       PS  2012
1261  1253                                     SoulCalibur II       GC  2012
1268  1260                                    Madden NFL 2001      PS2  2012
1274  1266                                        Rock Band 2      PS3  2012
1278  1270                          Medal of Honor: Frontline       XB  2012
1279  1271                                      Madden NFL 09      PS2  2012
1284  1276                                         The Sims 3      Wii  2012
1291  1283                                      Mass Effect 2      PS3  2012
1297  1289                                     SoulCalibur IV      PS3  2012
1300  1292                                Fight Night Round 3     X360  2013
1302  1294                                     Chrono Trigger       DS  2013
1303  1295                  Star Wars: The Force Unleashed II     X360  2013
1308  1300                    The SpongeBob SquarePants Movie      GBA  2013
1316  1308                                        Donkey Kong     2600  2013
1319  1311                                      Mass Effect 3      PS3  2013
1320  1312                     LEGO Batman 2: DC Super Heroes      Wii  2013
1326  1318                                         Diablo III     X360  2013
1327  1319                              Batman: Arkham Knight     XOne  2013
1328  1320                                           BioShock      PS3  2013
1347  1339                                          Far Cry 4      PS3  2013
1348  1340                          WWE SmackDown vs Raw 2008     X360  2013
1351  1343                              Need for Speed Rivals      PS3  2013
1353  1345                                       Dead Space 2      PS3  2013
1356  1348                                    Disney Infinity     X360  2013
1358  1350                Sonic's Ultimate Genesis Collection     X360  2013
1360  1352                                 Disney's DuckTales       GB  2013
1363  1355                 Dragon Quest VII: Warriors of Eden      3DS  2013
1369  1361                                  Sonic Generations     X360  2013
1372  1364                                         Dead Space     X360  2013
1375  1367                                 Tomb Raider (2013)      PS4  2013

In [22]:
pd.reset_option('display.max_rows')

In [23]:
# Look at in the all columns and Except Rank check once duplicates for remaining columns if you have delete it or think rank how rank is important
cols=df.columns.drop('Rank') # Here Rank is ignouring
cols

Index(['Name', 'Platform', 'Year', 'Month', 'Genre', 'Publisher', 'Country',
       'City', 'State', 'Region', 'NA_Sales', 'Global_Sales', 'NA_Profit',
       'Global_Profit'],
      dtype='object')

In [24]:
df.duplicated(subset=cols).sum()

np.int64(0)

In [25]:
# If we have duplicates then give all columns to drop them like 
# df.drop_duplicates(subset=cols, keep='first', inplace=True)
# df.duplicated(subset=cols).sum()

In [26]:
df.shape # After droping 16 duplicate Total 5909 - 16 = 5893

(5893, 15)

# Now Check Null Values

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5893 entries, 0 to 5908
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           5893 non-null   int64
 1   Name           5893 non-null   object
 2   Platform       5893 non-null   object
 3   Year           5893 non-null   int64
 4   Month          5893 non-null   object
 5   Genre          5893 non-null   object
 6   Publisher      5881 non-null   object
 7   Country        5893 non-null   object
 8   City           5893 non-null   object
 9   State          5893 non-null   object
 10  Region         5866 non-null   object
 11  NA_Sales       5893 non-null   object
 12  Global_Sales   5893 non-null   float64
 13  NA_Profit      5893 non-null   float64
 14  Global_Profit  5893 non-null   float64
dtypes: float64(3), int64(2), object(10)
memory usage: 736.6+ KB

In [28]:
df.isna().sum()

Rank              0
Name              0
Platform          0
Year              0
Month             0
Genre             0
Publisher        12
Country           0
City              0
State             0
Region           27
NA_Sales          0
Global_Sales      0
NA_Profit         0
Global_Profit     0
dtype: int64

In [29]:
df.isna().sum().sum()

np.int64(39)

In [30]:
df[df.isna().any(axis=1)]

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
13,10,Duck Hunt,NES,2010,Oct,Shooter,Nintendo,USA,Dallas,Texas,NaN,$26.93,28.31,8.079,8.493
38,35,Call of Duty: Black Ops II,PS3,2010,Nov,Shooter,Activision,United States,Stockton,California,NaN,4.99,14.03,1.497,4.209
53,50,Pokemon Omega Ruby/Pokemon Alpha Sapphire,3DS,2010,Feb,Role-Playing,Nintendo,United States,New York City,New York,NaN,4.23,11.33,1.269,3.399
84,78,FIFA 16,PS4,2010,Jun,Sports,Electronic Arts,United States,Carrollton,Texas,NaN,1.11,8.49,0.333,2.547
126,120,Uncharted 2: Among Thieves,PS3,2010,Dec,Action,Sony Computer Entertainment,United States,Los Angeles,California,NaN,3.27,6.73,0.981,2.019
210,204,Super Smash Bros. for Wii U and 3DS,WiiU,2010,Dec,Fighting,Nintendo,United States,New York City,New York,NaN,2.59,5.02,0.777,1.506
225,219,Assassin's Creed,PS3,2010,Mar,Adventure,Ubisoft,United States,Palm Coast,Florida,NaN,1.91,4.83,0.573,1.449
243,237,The Last of Us,PS4,2010,Sep,Action,Sony Computer Entertainment,United States,Lakeville,Minnesota,NaN,1.78,4.55,0.534,1.365
480,471,wwe Smackdown vs. Raw 2006,PS2,2010,Mar,Fighting,NaN,United States,New York City,New York,East,1.57,3.00,0.471,0.900
1313,1305,Triple Play 99,PS,2013,Aug,Sports,NaN,United States,Appleton,Wisconsin,Central,0.81,1.46,0.243,0.438
1675,1664,Shrek / Shrek 2 2-in-1 Gameboy Advance Video,GBA,2011,Jul,Misc,NaN,United States,San Diego,California,West,0.87,1.21,0.261,0.363
2235,2224,Bentley's Hackpack,GBA,2012,Mar,Misc,NaN,United States,New York City,New York,East,0.67,0.93,0.201,0.279
2453,2442,Harry Potter and the Order of the Phoenix,DS,2013,May,Action,Electronic Arts,United States,Philadelphia,Pennsylvania,NaN,0.28,0.85,0.084,0.255
2454,2443,Rampage World Tour,PS,2013,Jun,Action,GT Interactive,United States,Waco,Texas,NaN,0.47,0.85,0.141,0.255
2455,2444,Burnout Legends,PSP,2013,Jul,Racing,Electronic Arts,United States,Thousand Oaks,California,NaN,0.7,0.85,0.210,0.255
2456,2445,WWE 2K15,PS3,2013,Aug,Sports,Take-Two Interactive,United States,Freeport,Illinois,NaN,0.36,0.85,0.108,0.255
2604,2593,Tales of Destiny 2,PS2,2013,Dec,Role-Playing,Namco Bandai Games,United States,Harlingen,Texas,NaN,0,0.80,0.000,0.240
2605,2594,Capcom's Soccer Shootout,SNES,2013,Jan,Sports,Nintendo,United States,Louisville,Kentucky,NaN,0,0.80,0.000,0.240
2606,2595,Sniper: Ghost Warrior,PS3,2013,Feb,Shooter,City Interactive,United States,Louisville,Kentucky,NaN,0.26,0.80,0.078,0.240
2607,2596,The Godfather II,X360,2013,Mar,Action,Electronic Arts,United States,Louisville,Kentucky,NaN,0.47,0.79,0.141,0.237
3172,3161,Nicktoons Collection: Game Boy Advance Video V...,GBA,2012,Apr,Misc,NaN,Australia,Sydney,New South Wales,West,0.46,0.64,0.138,0.192
3179,3168,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2012,Nov,Misc,NaN,Australia,Sydney,New South Wales,West,0.46,0.64,0.138,0.192
3779,3768,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2014,November,Misc,NaN,Australia,Sydney,New South Wales,West,0.38,0.53,0.114,0.159
3979,3968,Chopper Command,2600,2014,Jul,Shooter,Activision,Australia,Sydney,New South Wales,NaN,0.47,0.50,0.141,0.150
3980,3969,Activision Anthology,PS2,2014,Aug,Misc,Activision,Australia,Sydney,New South Wales,NaN,0.25,0.50,0.075,0.150
3981,3970,Crash: Mind Over Mutant,PS2,2014,Sep,Platform,Vivendi Games,Australia,Sydney,New South Wales,NaN,0.25,0.50,0.075,0.150
3982,3971,WWE 2K16,X360,2014,Oct,Sports,Take-Two Interactive,Australia,Sydney,New South Wales,NaN,0.27,0.50,0.081,0.150
3983,3972,LEGO The Hobbit,X360,2014,Nov,Action,Warner Bros. Interactive Entertainment,Australia,Sydney,New South Wales,NaN,0.2,0.50,0.060,0.150
3984,3973,Babysitting Mama,Wii,2014,Dec,Simulation,505 Games,Australia,Sydney,New South Wales,NaN,0.34,0.50,0.102,0.150
3985,3974,Boogie,Wii,2014,Jan,Misc,Electronic Arts,Australia,Sydney,New South Wales,NaN,0.43,0.50,0.129,0.150
3986,3975,Theatrhythm: Final Fantasy,3DS,2014,Feb,Misc,Square Enix,Australia,Sydney,New South Wales,NaN,0.22,0.50,0.066,0.150
3987,3976,Bleach: Soul Resurreccion,PS3,2014,Mar,Fighting,Nippon Ichi Software,Australia,Sydney,New South Wales,NaN,0.27,0.50,0.081,0.150
3988,3977,Madden NFL 07,Wii,2014,Apr,Sports,Electronic Arts,Australia,Sydney,New South Wales,NaN,0.46,0.50,0.138,0.150
3989,3978,Rugrats in Paris: The Movie,N64,2014,May,Action,THQ,Australia,Sydney,New South Wales,NaN,0.4,0.50,0.120,0.150
4158,4147,Sonic the Hedgehog,PS3,2015,Jun,Platform,NaN,Australia,Sydney,New South Wales,West,0,0.48,0.000,0.144
4539,4528,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2015,Mar,Misc,NaN,Australia,Sydney,New South Wales,West,0.31,0.43,0.093,0.129
4648,4637,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2015,Apr,Misc,NaN,Australia,Sydney,New South Wales,West,0.3,0.42,0.090,0.126
5315,5304,Dragon Ball Z: Budokai Tenkaichi 2 (JP sales),Wii,2016,Nov,Action,NaN,Australia,Sydney,New South Wales,West,0.15,0.35,0.045,0.105
5660,5649,Cartoon Network Collection: Game Boy Advance V...,GBA,2017,Aug,Misc,NaN,Australia,Sydney,New South Wales,West,0.23,0.32,0.069,0.096

In [31]:
df.dropna() # After dropping 12+27=39 Null value Total= 5893 - 39=5854

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
0,1,Wii Sports,Wii,2010,Jan,Sports,Nintendo,United States,Fairfield,California,West,$41.49,82.74,12.447,24.822
1,2,Super Mario Bros.,NES,2010,Feb,Platform,Nintendo,United States,Edmonds,Washington,West,$29.08,40.24,8.724,12.072
2,3,Mario Kart Wii,Wii,2010,Mar,Racing,Nintendo,United States,Louisville,Kentucky,South,$15.85,35.82,4.755,10.746
3,4,Wii Sports Resort,Wii,2010,Apr,Sports,Nintendo,United States,Round Rock,Texas,Central,$15.75,33.00,4.725,9.900
4,5,Pokemon Red/Pokemon Blue,GB,2010,May,Role-Playing,Nintendo,United States,Nashville,Tennessee,South,$11.27,31.37,3.381,9.411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5904,5890,Crazy Taxi: Catch a Ride,GBA,2017,Sep,Racing,THQ,Australia,Sydney,New South Wales,West,0.21,0.30,0.063,0.090
5905,5891,MySims Party,DS,2017,Oct,Simulation,Electronic Arts,Australia,Sydney,New South Wales,West,0.15,0.30,0.045,0.090
5906,5892,Harry Potter and the Order of the Phoenix,X360,2017,Nov,Action,Electronic Arts,Australia,Sydney,New South Wales,West,0.24,0.30,0.072,0.090
5907,5893,Skylanders: SuperChargers,PS4,2017,Dec,Action,Activision,Australia,Sydney,New South Wales,West,0.17,0.30,0.051,0.090
5908,5894,Macross Digital Mission VF-X,PS,2017,Jan,Simulation,Namco Bandai Games,Australia,Sydney,New South Wales,West,0,0.30,0.000,0.090

# 1> Name

In [32]:
# '', '  ', ., :, /, &, +, -, ', (2015), !, 

import numpy as np
df['Name'] = (
    df['Name']
    .astype('string')
    .str.strip()
    .str.lower()
    .str.replace(r"[^a-zA-Z0-9\s]", '', regex=True)    # keeps only letters,numbers
    .str.replace(r'\s+', ' ', regex=True)              # collapse multiple spaces
    .str.strip()                                       # strip
    .replace(r'^\s*$', np.nan, regex=True)
    .str.title()                                       # capitalize words
)
df['Name'].sample(10)

5220               Sabans Power Rangers Lightspeed Rescue
1007                                    Hitman Absolution
3761                                               Popeye
1298                                           Mario Golf
1019                                      Disneys Aladdin
234                  The Lord Of The Rings The Two Towers
1749                                         Mirrors Edge
4777                           Marvel Ultimate Alliance 2
1908    Spongebob Squarepants Revenge Of The Flying Du...
1544                                Guitar Hero Aerosmith
Name: Name, dtype: string

# 2>  category platform ->

In [33]:
df['Platform'].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC',
       'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS'], dtype=object)

In [34]:
df['Platform']=(df['Platform']
    .str.strip()
    .str.lower()
    .replace(r'^\s*$', np.nan, regex=True)
    .str.upper()
    .astype('category')
               )

df['Platform'].sample(10)

5012     PSP
2650      DS
3301      XB
107      WII
5896      DS
5570      GC
5487      XB
2933    WIIU
2940     PS2
2111     PS3
Name: Platform, dtype: category
Categories (26, object): ['2600', '3DS', 'DC', 'DS', ..., 'WS', 'X360', 'XB', 'XONE']

# Year int64 - we dont need change any values because no null values and data type is int64 so it cleaned

In [35]:
df['Year'].sample(50)

2379    2012
3684    2014
518     2010
1666    2011
5360    2016
4645    2015
3096    2011
4812    2016
2303    2012
4203    2015
5800    2017
585     2010
2825    2010
305     2010
1217    2012
2160    2012
4300    2015
981     2011
4517    2015
3672    2014
4876    2016
4043    2014
1385    2014
4903    2016
3686    2014
1444    2014
4061    2014
1196    2012
2855    2010
3830    2014
4102    2014
1030    2011
5841    2017
3369    2012
4060    2014
2903    2011
2258    2012
40      2010
37      2010
2264    2012
843     2011
1965    2012
1724    2011
5511    2017
4237    2015
2850    2010
3268    2012
2336    2012
3663    2014
2675    2014
Name: Year, dtype: int64

# Month

In [36]:
df['Month'].unique()

array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
       'Oct', 'Nov', 'Dec', 'October', 'November'], dtype=object)

In [37]:
pd.set_option('display.max_rows',None)
df['Month'] # Eg:- index 268 see October , index 3767 see Novermber so change it to Oct,Nov

0            Jan
1            Feb
2            Mar
3            Apr
4            May
5            Jun
6            Jul
7            Aug
8            Sep
13           Oct
14           Nov
15           Dec
16           Jan
17           Feb
18           Mar
19           Apr
20           May
21           Jun
22           Jul
23           Aug
24           Sep
25           Oct
26           Nov
27           Dec
28           Jan
29           Feb
30           Mar
31           Apr
32           May
33           Jun
34           Jul
35           Aug
36           Sep
37           Oct
38           Nov
39           Dec
40           Jan
41           Feb
42           Mar
43           Apr
44           May
45           Jun
46           Jul
47           Aug
48           Sep
49           Oct
50           Nov
51           Dec
52           Jan
53           Feb
54           Mar
55           Apr
56           May
57           Jun
58           Jul
59           Aug
60           Sep
61           Oct
62           Nov
63           Dec
67           Jan
68           Feb
69           Mar
70           Apr
71           May
72           Jun
73           Jul
74           Aug
75           Sep
76           Oct
77           Nov
78           Dec
79           Jan
80           Feb
81           Mar
82           Apr
83           May
84           Jun
85           Jul
86           Aug
87           Sep
88           Oct
89           Nov
90           Dec
91           Jan
92           Feb
93           Mar
94           Apr
95           May
96           Jun
97           Jul
98           Aug
99           Sep
100          Oct
101          Nov
102          Dec
103          Jan
104          Feb
105          Mar
106          Apr
107          May
108          Jun
109          Jul
110          Aug
111          Sep
112          Oct
113          Nov
114          Dec
115          Jan
116          Feb
117          Mar
118          Apr
119          May
120          Jun
121          Jul
122          Aug
123          Sep
124          Oct
125          Nov
126          Dec
127          Jan
128          Feb
129          Mar
130          Apr
131          May
132          Jun
133          Jul
134          Aug
135          Sep
136          Oct
137          Nov
138          Dec
139          Jan
140          Feb
141          Mar
142          Apr
143          May
144          Jun
145          Jul
146          Aug
147          Sep
148          Oct
149          Nov
150          Dec
151          Jan
152          Feb
153          Mar
154          Apr
155          May
156          Jun
157          Jul
158          Aug
159          Sep
160          Oct
161          Nov
162          Dec
163          Jan
164          Feb
165          Mar
166          Apr
167          May
168          Jun
169          Jul
170          Aug
171          Sep
172      October
173          Nov
174          Dec
175          Jan
176          Feb
177          Mar
178          Apr
179          May
180          Jun
181          Jul
182          Aug
183          Sep
184      October
185          Nov
186          Dec
187          Jan
188          Feb
189          Mar
190          Apr
191          May
192          Jun
193          Jul
194          Aug
195          Sep
196      October
197          Nov
198          Dec
199          Jan
200          Feb
201          Mar
202          Apr
203          May
204          Jun
205          Jul
206          Aug
207          Sep
208      October
209          Nov
210          Dec
211          Jan
212          Feb
213          Mar
214          Apr
215          May
216          Jun
217          Jul
218          Aug
219          Sep
220      October
221          Nov
222          Dec
223          Jan
224          Feb
225          Mar
226          Apr
227          May
228          Jun
229          Jul
230          Aug
231          Sep
232      October
233          Nov
234          Dec
235          Jan
236          Feb
237          Mar
238          Apr
239          May
240          Jun
241          Jul
242          Aug
243          Sep
244      October
245          Nov
246          Dec
247          Jan
248          Feb
249          Mar
250          Apr
251          May
252          Jun
253          Jul
254          Aug
255          Sep
256      October
257          Nov
258          Dec
259          Jan
260          Feb
261          Mar
262          Apr
263          May
264          Jun
265          Jul
266          Aug
267          Sep
268      October
269          Nov
270          Dec
271          Jan
272          Feb
273          Mar
274          Apr
275          May
276          Jun
277          Jul
278          Aug
279          Sep
280      October
281          Nov
282          Dec
283          Jan
284          Feb
285          Mar
286          Apr
287          May
288          Jun
289          Jul
290          Aug
291          Sep
292      October
293          Nov
294          Dec
295          Jan
296          Feb
297          Mar
298          Apr
299          May
300          Jun
301          Jul
302          Aug
303          Sep
304          Oct
305          Nov
306          Dec
307          Jan
308          Feb
309          Mar
310          Apr
311          May
312          Jun
313          Jul
314          Aug
315          Sep
316          Oct
317          Nov
318          Dec
319          Jan
320          Feb
321          Mar
322          Apr
323          May
324          Jun
325          Jul
326          Aug
327          Sep
328          Oct
329          Nov
330          Dec
331          Jan
332          Feb
333          Mar
334          Apr
335          May
336          Jun
337          Jul
338          Aug
339          Sep
340          Oct
341          Nov
342          Dec
343          Jan
344          Feb
345          Mar
346          Apr
347          May
348          Jun
349          Jul
350          Aug
351          Sep
352          Oct
353          Nov
354          Dec
355          Jan
356          Feb
357          Mar
358          Apr
359          May
360          Jun
361          Jul
362          Aug
363          Sep
364          Oct
365          Nov
366          Dec
367          Jan
368          Feb
369          Mar
370          Apr
371          May
372          Jun
373          Jul
374          Aug
375          Sep
376      October
377          Nov
378          Dec
379          Jan
383          Feb
384          Mar
385          Apr
386          May
387          Jun
388          Jul
389          Aug
390          Sep
391      October
392          Nov
393          Dec
394          Jan
395          Feb
396          Mar
397          Apr
398          May
399          Jun
400          Jul
401          Aug
402          Sep
403      October
404          Nov
405          Dec
406          Jan
407          Feb
408          Mar
409          Apr
410          May
411          Jun
412          Jul
413          Aug
414          Sep
415      October
416          Nov
417          Dec
418          Jan
419          Feb
420          Mar
421          Apr
422          May
423          Jun
424          Jul
425          Aug
426          Sep
427      October
428          Nov
429          Dec
430          Jan
431          Feb
432          Mar
433          Apr
434          May
435          Jun
436          Jul
437          Aug
438          Sep
439      October
440          Nov
441          Dec
442          Jan
443          Feb
444          Mar
445          Apr
446          May
447          Jun
448          Jul
449          Aug
450          Sep
451      October
452          Nov
453          Dec
454          Jan
455          Feb
456          Mar
457          Apr
458          May
459          Jun
460          Jul
461          Aug
462          Sep
463      October
464          Nov
465          Dec
466          Jan
467          Feb
468          Mar
469          Apr
470          May
471          Jun
472          Jul
473          Aug
474          Sep
475      October
476          Nov
477          Dec
478          Jan
479          Feb
480          Mar
481          Apr
482          May
483          Jun
484          Jul
485          Aug
486          Sep
487          Oct
488          Nov
489          Dec
490          Jan
491          Feb
492          Mar
493          Apr
494          May
495          Jun
496          Jul
497          Aug
498          Sep
499          Oct
500          Nov
501          Dec
502          Jan
503          Feb
504          Mar
505          Apr
506          May
507          Jun
508          Jul
509          Aug
510          Sep
511          Oct
512          Nov
513          Dec
514          Jan
515          Feb
516          Mar
517          Apr
518          May
519          Jun
520          Jul
521          Aug
522          Sep
523          Oct
524          Nov
525          Dec
526          Jan
527          Feb
528          Mar
529          Apr
530          May
531          Jun
532          Jul
533          Aug
534          Sep
535          Oct
536          Nov
537          Dec
538          Jan
539          Feb
540          Mar
541          Apr
542          May
543          Jun
544          Jul
545          Aug
546          Sep
547          Oct
548          Nov
549          Dec
550          Jan
551          Feb
552          Mar
553          Apr
554          May
555          Jun
556          Jul
557          Aug
558          Sep
559          Oct
560          Nov
561          Dec
562          Jan
563          Feb
564          Mar
565          Apr
566          May
567          Jun
568          Jul
569          Aug
570          Sep
571          Oct
572          Nov
573          Dec
574          Jan
575          Feb
576          Mar
577          Apr
578          May
579          Jun
580          Jul
581          Aug
582          Sep
583          Oct
584          Nov
585          Dec
586          Jan
587          Feb
588          Mar
589          Apr
590          May
591          Jun
592          Jul
593          Aug
594          Sep
595          Oct
596          Nov
597          Dec
598          Jan
599          Feb
600          Mar
601          Apr
602          May
603          Jun
604          Jul
605          Aug
606          Sep
607          Oct
608          Nov
609          Dec
610          Jan
611          Feb
612          Mar
613          Apr
614          May
615          Jun
616          Jul
617          Aug
618          Sep
619          Oct
620          Nov
621          Dec
622          Jan
623          Feb
624          Mar
625          Apr
626          May
627          Jun
628          Jul
629          Aug
630          Sep
631          Oct
632          Nov
633          Dec
634          Jan
635          Feb
636          Mar
637          Apr
638          May
639          Jun
640          Jul
641          Aug
642          Sep
643          Oct
644          Nov
645          Dec
646          Jan
647          Feb
648          Mar
649          Apr
650          May
651          Jun
652          Jul
653          Aug
654          Sep
655          Oct
656          Nov
657          Dec
658          Jan
659          Feb
660          Mar
661          Apr
662          May
663          Jun
664          Jul
665          Aug
666          Sep
667          Oct
668          Nov
669          Dec
670          Jan
671          Feb
672          Mar
673          Apr
674          May
675          Jun
676          Jul
677          Aug
678          Sep
679          Oct
680          Nov
681          Dec
682          Jan
683          Feb
684          Mar
685          Apr
686          May
687          Jun
688          Jul
689          Aug
690          Sep
691          Oct
692          Nov
693          Dec
694          Jan
695          Feb
696          Mar
697          Apr
698          May
699          Jun
700          Jul
701          Aug
702          Sep
703          Oct
704          Nov
705          Dec
706          Jan
707          Feb
708          Mar
709          Apr
710          May
711          Jun
712          Jul
713          Aug
714          Sep
715          Oct
716          Nov
717          Dec
718          Jan
719          Feb
720          Mar
721          Apr
722          May
723          Jun
724          Jul
725          Aug
726          Sep
727          Oct
728          Nov
729          Dec
730          Jan
731          Feb
732          Mar
733          Apr
734          May
735          Jun
736          Jul
737          Aug
738          Sep
739          Oct
740          Nov
741          Dec
742          Jan
743          Feb
744          Mar
745          Apr
746          May
747          Jun
748          Jul
749          Aug
750          Sep
751          Oct
752          Nov
753          Dec
754          Jan
755          Feb
756          Mar
757          Apr
758          May
759          Jun
760          Jul
761          Aug
762          Sep
763          Oct
764          Nov
765          Dec
766          Jan
767          Feb
768          Mar
769          Apr
770          May
771          Jun
772          Jul
773          Aug
774          Sep
775          Oct
776          Nov
777          Dec
778          Jan
779          Feb
780          Mar
781          Apr
782          May
783          Jun
784          Jul
785          Aug
786          Sep
787          Oct
788          Nov
789          Dec
790          Jan
791          Feb
792          Mar
793          Apr
794          May
795          Jun
796          Jul
797          Aug
798          Sep
799          Oct
800          Nov
801          Dec
802          Jan
803          Feb
804          Mar
805          Apr
806          May
807          Jun
808          Jul
809          Aug
810          Sep
811          Oct
812          Nov
813          Dec
814          Jan
815          Feb
816          Mar
817          Apr
818          May
819          Jun
820          Jul
821          Aug
822          Sep
823          Oct
824          Nov
825          Dec
826          Jan
827          Feb
828          Mar
829          Apr
830          May
831          Jun
832          Jul
833          Aug
834          Sep
835          Oct
836          Nov
837          Dec
838          Jan
839          Feb
840          Mar
841          Apr
842          May
843          Jun
844          Jul
845          Aug
846          Sep
847          Oct
848          Nov
849          Dec
850          Jan
851          Feb
852          Mar
853          Apr
854          May
855          Jun
856          Jul
857          Aug
858          Sep
859          Oct
860          Nov
861          Dec
862          Jan
863          Feb
864          Mar
865          Apr
866          May
867          Jun
868          Jul
869          Aug
870          Sep
871          Oct
872          Nov
873          Dec
874          Jan
875          Feb
876          Mar
877          Apr
878          May
879          Jun
880          Jul
881          Aug
882          Sep
883          Oct
884          Nov
885          Dec
886          Jan
887          Feb
888          Mar
889          Apr
890          May
891          Jun
892          Jul
893          Aug
894          Sep
895          Oct
896          Nov
897          Dec
898          Jan
899          Feb
900          Mar
901          Apr
902          May
903          Jun
904          Jul
905          Aug
906          Sep
907          Oct
908          Nov
909          Dec
910          Jan
911          Feb
912          Mar
913          Apr
914          May
915          Jun
916          Jul
917          Aug
918          Sep
919          Oct
920          Nov
921          Dec
922          Jan
923          Feb
924          Mar
925          Apr
926          May
927          Jun
928          Jul
929          Aug
930          Sep
931          Oct
932          Nov
933          Dec
934          Jan
935          Feb
936          Mar
937          Apr
938          May
939          Jun
940          Jul
941          Aug
942          Sep
943          Oct
944          Nov
945          Dec
946          Jan
947          Feb
948          Mar
949          Apr
950          May
951          Jun
952          Jul
953          Aug
954          Sep
955          Oct
956          Nov
957          Dec
958          Jan
959          Feb
960          Mar
961          Apr
962          May
963          Jun
964          Jul
965          Aug
966          Sep
967          Oct
968          Nov
969          Dec
970          Jan
971          Feb
972          Mar
973          Apr
974          May
975          Jun
976          Jul
977          Aug
978          Sep
979          Oct
980          Nov
981          Dec
982          Jan
983          Feb
984          Mar
985          Apr
986          May
987          Jun
988          Jul
989          Aug
990          Sep
991          Oct
992          Nov
993          Dec
994          Jan
995          Feb
996          Mar
997          Apr
998          May
999          Jun
1000         Jul
1001         Aug
1002         Sep
1003         Oct
1004         Nov
1005         Dec
1006         Jan
1007         Feb
1008         Mar
1009         Apr
1010         May
1011         Jun
1012         Jul
1013         Aug
1014         Sep
1015         Oct
1016         Nov
1017         Dec
1018         Jan
1019         Feb
1020         Mar
1021         Apr
1022         May
1023         Jun
1024         Jul
1025         Aug
1026         Sep
1027         Oct
1028         Nov
1029         Dec
1030         Jan
1031         Feb
1032         Mar
1033         Apr
1034         May
1035         Jun
1036         Jul
1037         Aug
1038         Sep
1039         Oct
1040         Nov
1041         Dec
1042         Jan
1043         Feb
1044         Mar
1045         Apr
1046         May
1047         Jun
1048         Jul
1049         Aug
1050         Sep
1051         Oct
1052         Nov
1053         Dec
1054         Jan
1055         Feb
1056         Mar
1057         Apr
1058         May
1059         Jun
1060         Jul
1061         Aug
1062         Sep
1063         Oct
1064         Nov
1065         Dec
1066         Jan
1067         Feb
1068         Mar
1069         Apr
1070         May
1071         Jun
1072         Jul
1073         Aug
1074         Sep
1075         Oct
1076         Nov
1077         Dec
1078         Jan
1079         Feb
1080         Mar
1081         Apr
1082         May
1083         Jun
1084         Jul
1085         Aug
1086         Sep
1087         Oct
1088         Nov
1089         Dec
1090         Jan
1091         Feb
1092         Mar
1093         Apr
1094         May
1095         Jun
1096         Jul
1097         Aug
1098         Sep
1099         Oct
1100         Nov
1101         Dec
1102         Jan
1103         Feb
1104         Mar
1105         Apr
1106         May
1107         Jun
1108         Jul
1109         Aug
1110         Sep
1111         Oct
1112         Nov
1113         Dec
1114         Jan
1115         Feb
1116         Mar
1117         Apr
1118         May
1119         Jun
1120         Jul
1121         Aug
1122         Sep
1123         Oct
1124         Nov
1125         Dec
1126         Jan
1127         Feb
1128         Mar
1129         Apr
1130         May
1131         Jun
1132         Jul
1133         Aug
1134         Sep
1135         Oct
1136         Nov
1137         Dec
1138         Jan
1139         Feb
1140         Mar
1141         Apr
1142         May
1143         Jun
1144         Jul
1145         Aug
1146         Sep
1147         Oct
1148         Nov
1149         Dec
1150         Jan
1151         Feb
1152         Mar
1153         Apr
1154         May
1155         Jun
1156         Jul
1157         Aug
1158         Sep
1159         Oct
1160         Nov
1161         Dec
1162         Jan
1163         Feb
1164         Mar
1165         Apr
1166         May
1167         Jun
1168         Jul
1169         Aug
1170         Sep
1171         Oct
1172         Nov
1173         Dec
1174         Jan
1175         Feb
1176         Mar
1177         Apr
1178         May
1179         Jun
1180         Jul
1181         Aug
1182         Sep
1183         Oct
1184         Nov
1185         Dec

In [38]:
# array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
#        'Oct', 'Nov', 'Dec', 'October', 'November'], dtype=object)

# o-c :-  october,november -> ,Oct, Nov
df['Month']=(df['Month']
    .astype('string')
    .str.strip()
    .str.lower()
    .replace({'october':'oct', 'november':'nov'})
    .str.capitalize()
    .astype('category')
            )

# ['Jan', 'Feb', 'Mar', 'Apr', 'May', ..., 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
# Length: 12
# Categories (12, string): [Apr, Aug, Dec, Feb, ..., May, Nov, Oct, Sep]

# valid_month=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
#        'Oct', 'Nov', 'Dec']

# df.loc[~df['Month'].isin(valid_month), 'Month']=np.nan

df['Month']
# Eg:- index 268 see October , index 3767 see Novermber so change it to Oct,Nov

0       Jan
1       Feb
2       Mar
3       Apr
4       May
5       Jun
6       Jul
7       Aug
8       Sep
13      Oct
14      Nov
15      Dec
16      Jan
17      Feb
18      Mar
19      Apr
20      May
21      Jun
22      Jul
23      Aug
24      Sep
25      Oct
26      Nov
27      Dec
28      Jan
29      Feb
30      Mar
31      Apr
32      May
33      Jun
34      Jul
35      Aug
36      Sep
37      Oct
38      Nov
39      Dec
40      Jan
41      Feb
42      Mar
43      Apr
44      May
45      Jun
46      Jul
47      Aug
48      Sep
49      Oct
50      Nov
51      Dec
52      Jan
53      Feb
54      Mar
55      Apr
56      May
57      Jun
58      Jul
59      Aug
60      Sep
61      Oct
62      Nov
63      Dec
67      Jan
68      Feb
69      Mar
70      Apr
71      May
72      Jun
73      Jul
74      Aug
75      Sep
76      Oct
77      Nov
78      Dec
79      Jan
80      Feb
81      Mar
82      Apr
83      May
84      Jun
85      Jul
86      Aug
87      Sep
88      Oct
89      Nov
90      Dec
91      Jan
92      Feb
93      Mar
94      Apr
95      May
96      Jun
97      Jul
98      Aug
99      Sep
100     Oct
101     Nov
102     Dec
103     Jan
104     Feb
105     Mar
106     Apr
107     May
108     Jun
109     Jul
110     Aug
111     Sep
112     Oct
113     Nov
114     Dec
115     Jan
116     Feb
117     Mar
118     Apr
119     May
120     Jun
121     Jul
122     Aug
123     Sep
124     Oct
125     Nov
126     Dec
127     Jan
128     Feb
129     Mar
130     Apr
131     May
132     Jun
133     Jul
134     Aug
135     Sep
136     Oct
137     Nov
138     Dec
139     Jan
140     Feb
141     Mar
142     Apr
143     May
144     Jun
145     Jul
146     Aug
147     Sep
148     Oct
149     Nov
150     Dec
151     Jan
152     Feb
153     Mar
154     Apr
155     May
156     Jun
157     Jul
158     Aug
159     Sep
160     Oct
161     Nov
162     Dec
163     Jan
164     Feb
165     Mar
166     Apr
167     May
168     Jun
169     Jul
170     Aug
171     Sep
172     Oct
173     Nov
174     Dec
175     Jan
176     Feb
177     Mar
178     Apr
179     May
180     Jun
181     Jul
182     Aug
183     Sep
184     Oct
185     Nov
186     Dec
187     Jan
188     Feb
189     Mar
190     Apr
191     May
192     Jun
193     Jul
194     Aug
195     Sep
196     Oct
197     Nov
198     Dec
199     Jan
200     Feb
201     Mar
202     Apr
203     May
204     Jun
205     Jul
206     Aug
207     Sep
208     Oct
209     Nov
210     Dec
211     Jan
212     Feb
213     Mar
214     Apr
215     May
216     Jun
217     Jul
218     Aug
219     Sep
220     Oct
221     Nov
222     Dec
223     Jan
224     Feb
225     Mar
226     Apr
227     May
228     Jun
229     Jul
230     Aug
231     Sep
232     Oct
233     Nov
234     Dec
235     Jan
236     Feb
237     Mar
238     Apr
239     May
240     Jun
241     Jul
242     Aug
243     Sep
244     Oct
245     Nov
246     Dec
247     Jan
248     Feb
249     Mar
250     Apr
251     May
252     Jun
253     Jul
254     Aug
255     Sep
256     Oct
257     Nov
258     Dec
259     Jan
260     Feb
261     Mar
262     Apr
263     May
264     Jun
265     Jul
266     Aug
267     Sep
268     Oct
269     Nov
270     Dec
271     Jan
272     Feb
273     Mar
274     Apr
275     May
276     Jun
277     Jul
278     Aug
279     Sep
280     Oct
281     Nov
282     Dec
283     Jan
284     Feb
285     Mar
286     Apr
287     May
288     Jun
289     Jul
290     Aug
291     Sep
292     Oct
293     Nov
294     Dec
295     Jan
296     Feb
297     Mar
298     Apr
299     May
300     Jun
301     Jul
302     Aug
303     Sep
304     Oct
305     Nov
306     Dec
307     Jan
308     Feb
309     Mar
310     Apr
311     May
312     Jun
313     Jul
314     Aug
315     Sep
316     Oct
317     Nov
318     Dec
319     Jan
320     Feb
321     Mar
322     Apr
323     May
324     Jun
325     Jul
326     Aug
327     Sep
328     Oct
329     Nov
330     Dec
331     Jan
332     Feb
333     Mar
334     Apr
335     May
336     Jun
337     Jul
338     Aug
339     Sep
340     Oct
341     Nov
342     Dec
343     Jan
344     Feb
345     Mar
346     Apr
347     May
348     Jun
349     Jul
350     Aug
351     Sep
352     Oct
353     Nov
354     Dec
355     Jan
356     Feb
357     Mar
358     Apr
359     May
360     Jun
361     Jul
362     Aug
363     Sep
364     Oct
365     Nov
366     Dec
367     Jan
368     Feb
369     Mar
370     Apr
371     May
372     Jun
373     Jul
374     Aug
375     Sep
376     Oct
377     Nov
378     Dec
379     Jan
383     Feb
384     Mar
385     Apr
386     May
387     Jun
388     Jul
389     Aug
390     Sep
391     Oct
392     Nov
393     Dec
394     Jan
395     Feb
396     Mar
397     Apr
398     May
399     Jun
400     Jul
401     Aug
402     Sep
403     Oct
404     Nov
405     Dec
406     Jan
407     Feb
408     Mar
409     Apr
410     May
411     Jun
412     Jul
413     Aug
414     Sep
415     Oct
416     Nov
417     Dec
418     Jan
419     Feb
420     Mar
421     Apr
422     May
423     Jun
424     Jul
425     Aug
426     Sep
427     Oct
428     Nov
429     Dec
430     Jan
431     Feb
432     Mar
433     Apr
434     May
435     Jun
436     Jul
437     Aug
438     Sep
439     Oct
440     Nov
441     Dec
442     Jan
443     Feb
444     Mar
445     Apr
446     May
447     Jun
448     Jul
449     Aug
450     Sep
451     Oct
452     Nov
453     Dec
454     Jan
455     Feb
456     Mar
457     Apr
458     May
459     Jun
460     Jul
461     Aug
462     Sep
463     Oct
464     Nov
465     Dec
466     Jan
467     Feb
468     Mar
469     Apr
470     May
471     Jun
472     Jul
473     Aug
474     Sep
475     Oct
476     Nov
477     Dec
478     Jan
479     Feb
480     Mar
481     Apr
482     May
483     Jun
484     Jul
485     Aug
486     Sep
487     Oct
488     Nov
489     Dec
490     Jan
491     Feb
492     Mar
493     Apr
494     May
495     Jun
496     Jul
497     Aug
498     Sep
499     Oct
500     Nov
501     Dec
502     Jan
503     Feb
504     Mar
505     Apr
506     May
507     Jun
508     Jul
509     Aug
510     Sep
511     Oct
512     Nov
513     Dec
514     Jan
515     Feb
516     Mar
517     Apr
518     May
519     Jun
520     Jul
521     Aug
522     Sep
523     Oct
524     Nov
525     Dec
526     Jan
527     Feb
528     Mar
529     Apr
530     May
531     Jun
532     Jul
533     Aug
534     Sep
535     Oct
536     Nov
537     Dec
538     Jan
539     Feb
540     Mar
541     Apr
542     May
543     Jun
544     Jul
545     Aug
546     Sep
547     Oct
548     Nov
549     Dec
550     Jan
551     Feb
552     Mar
553     Apr
554     May
555     Jun
556     Jul
557     Aug
558     Sep
559     Oct
560     Nov
561     Dec
562     Jan
563     Feb
564     Mar
565     Apr
566     May
567     Jun
568     Jul
569     Aug
570     Sep
571     Oct
572     Nov
573     Dec
574     Jan
575     Feb
576     Mar
577     Apr
578     May
579     Jun
580     Jul
581     Aug
582     Sep
583     Oct
584     Nov
585     Dec
586     Jan
587     Feb
588     Mar
589     Apr
590     May
591     Jun
592     Jul
593     Aug
594     Sep
595     Oct
596     Nov
597     Dec
598     Jan
599     Feb
600     Mar
601     Apr
602     May
603     Jun
604     Jul
605     Aug
606     Sep
607     Oct
608     Nov
609     Dec
610     Jan
611     Feb
612     Mar
613     Apr
614     May
615     Jun
616     Jul
617     Aug
618     Sep
619     Oct
620     Nov
621     Dec
622     Jan
623     Feb
624     Mar
625     Apr
626     May
627     Jun
628     Jul
629     Aug
630     Sep
631     Oct
632     Nov
633     Dec
634     Jan
635     Feb
636     Mar
637     Apr
638     May
639     Jun
640     Jul
641     Aug
642     Sep
643     Oct
644     Nov
645     Dec
646     Jan
647     Feb
648     Mar
649     Apr
650     May
651     Jun
652     Jul
653     Aug
654     Sep
655     Oct
656     Nov
657     Dec
658     Jan
659     Feb
660     Mar
661     Apr
662     May
663     Jun
664     Jul
665     Aug
666     Sep
667     Oct
668     Nov
669     Dec
670     Jan
671     Feb
672     Mar
673     Apr
674     May
675     Jun
676     Jul
677     Aug
678     Sep
679     Oct
680     Nov
681     Dec
682     Jan
683     Feb
684     Mar
685     Apr
686     May
687     Jun
688     Jul
689     Aug
690     Sep
691     Oct
692     Nov
693     Dec
694     Jan
695     Feb
696     Mar
697     Apr
698     May
699     Jun
700     Jul
701     Aug
702     Sep
703     Oct
704     Nov
705     Dec
706     Jan
707     Feb
708     Mar
709     Apr
710     May
711     Jun
712     Jul
713     Aug
714     Sep
715     Oct
716     Nov
717     Dec
718     Jan
719     Feb
720     Mar
721     Apr
722     May
723     Jun
724     Jul
725     Aug
726     Sep
727     Oct
728     Nov
729     Dec
730     Jan
731     Feb
732     Mar
733     Apr
734     May
735     Jun
736     Jul
737     Aug
738     Sep
739     Oct
740     Nov
741     Dec
742     Jan
743     Feb
744     Mar
745     Apr
746     May
747     Jun
748     Jul
749     Aug
750     Sep
751     Oct
752     Nov
753     Dec
754     Jan
755     Feb
756     Mar
757     Apr
758     May
759     Jun
760     Jul
761     Aug
762     Sep
763     Oct
764     Nov
765     Dec
766     Jan
767     Feb
768     Mar
769     Apr
770     May
771     Jun
772     Jul
773     Aug
774     Sep
775     Oct
776     Nov
777     Dec
778     Jan
779     Feb
780     Mar
781     Apr
782     May
783     Jun
784     Jul
785     Aug
786     Sep
787     Oct
788     Nov
789     Dec
790     Jan
791     Feb
792     Mar
793     Apr
794     May
795     Jun
796     Jul
797     Aug
798     Sep
799     Oct
800     Nov
801     Dec
802     Jan
803     Feb
804     Mar
805     Apr
806     May
807     Jun
808     Jul
809     Aug
810     Sep
811     Oct
812     Nov
813     Dec
814     Jan
815     Feb
816     Mar
817     Apr
818     May
819     Jun
820     Jul
821     Aug
822     Sep
823     Oct
824     Nov
825     Dec
826     Jan
827     Feb
828     Mar
829     Apr
830     May
831     Jun
832     Jul
833     Aug
834     Sep
835     Oct
836     Nov
837     Dec
838     Jan
839     Feb
840     Mar
841     Apr
842     May
843     Jun
844     Jul
845     Aug
846     Sep
847     Oct
848     Nov
849     Dec
850     Jan
851     Feb
852     Mar
853     Apr
854     May
855     Jun
856     Jul
857     Aug
858     Sep
859     Oct
860     Nov
861     Dec
862     Jan
863     Feb
864     Mar
865     Apr
866     May
867     Jun
868     Jul
869     Aug
870     Sep
871     Oct
872     Nov
873     Dec
874     Jan
875     Feb
876     Mar
877     Apr
878     May
879     Jun
880     Jul
881     Aug
882     Sep
883     Oct
884     Nov
885     Dec
886     Jan
887     Feb
888     Mar
889     Apr
890     May
891     Jun
892     Jul
893     Aug
894     Sep
895     Oct
896     Nov
897     Dec
898     Jan
899     Feb
900     Mar
901     Apr
902     May
903     Jun
904     Jul
905     Aug
906     Sep
907     Oct
908     Nov
909     Dec
910     Jan
911     Feb
912     Mar
913     Apr
914     May
915     Jun
916     Jul
917     Aug
918     Sep
919     Oct
920     Nov
921     Dec
922     Jan
923     Feb
924     Mar
925     Apr
926     May
927     Jun
928     Jul
929     Aug
930     Sep
931     Oct
932     Nov
933     Dec
934     Jan
935     Feb
936     Mar
937     Apr
938     May
939     Jun
940     Jul
941     Aug
942     Sep
943     Oct
944     Nov
945     Dec
946     Jan
947     Feb
948     Mar
949     Apr
950     May
951     Jun
952     Jul
953     Aug
954     Sep
955     Oct
956     Nov
957     Dec
958     Jan
959     Feb
960     Mar
961     Apr
962     May
963     Jun
964     Jul
965     Aug
966     Sep
967     Oct
968     Nov
969     Dec
970     Jan
971     Feb
972     Mar
973     Apr
974     May
975     Jun
976     Jul
977     Aug
978     Sep
979     Oct
980     Nov
981     Dec
982     Jan
983     Feb
984     Mar
985     Apr
986     May
987     Jun
988     Jul
989     Aug
990     Sep
991     Oct
992     Nov
993     Dec
994     Jan
995     Feb
996     Mar
997     Apr
998     May
999     Jun
1000    Jul
1001    Aug
1002    Sep
1003    Oct
1004    Nov
1005    Dec
1006    Jan
1007    Feb
1008    Mar
1009    Apr
1010    May
1011    Jun
1012    Jul
1013    Aug
1014    Sep
1015    Oct
1016    Nov
1017    Dec
1018    Jan
1019    Feb
1020    Mar
1021    Apr
1022    May
1023    Jun
1024    Jul
1025    Aug
1026    Sep
1027    Oct
1028    Nov
1029    Dec
1030    Jan
1031    Feb
1032    Mar
1033    Apr
1034    May
1035    Jun
1036    Jul
1037    Aug
1038    Sep
1039    Oct
1040    Nov
1041    Dec
1042    Jan
1043    Feb
1044    Mar
1045    Apr
1046    May
1047    Jun
1048    Jul
1049    Aug
1050    Sep
1051    Oct
1052    Nov
1053    Dec
1054    Jan
1055    Feb
1056    Mar
1057    Apr
1058    May
1059    Jun
1060    Jul
1061    Aug
1062    Sep
1063    Oct
1064    Nov
1065    Dec
1066    Jan
1067    Feb
1068    Mar
1069    Apr
1070    May
1071    Jun
1072    Jul
1073    Aug
1074    Sep
1075    Oct
1076    Nov
1077    Dec
1078    Jan
1079    Feb
1080    Mar
1081    Apr
1082    May
1083    Jun
1084    Jul
1085    Aug
1086    Sep
1087    Oct
1088    Nov
1089    Dec
1090    Jan
1091    Feb
1092    Mar
1093    Apr
1094    May
1095    Jun
1096    Jul
1097    Aug
1098    Sep
1099    Oct
1100    Nov
1101    Dec
1102    Jan
1103    Feb
1104    Mar
1105    Apr
1106    May
1107    Jun
1108    Jul
1109    Aug
1110    Sep
1111    Oct
1112    Nov
1113    Dec
1114    Jan
1115    Feb
1116    Mar
1117    Apr
1118    May
1119    Jun
1120    Jul
1121    Aug
1122    Sep
1123    Oct
1124    Nov
1125    Dec
1126    Jan
1127    Feb
1128    Mar
1129    Apr
1130    May
1131    Jun
1132    Jul
1133    Aug
1134    Sep
1135    Oct
1136    Nov
1137    Dec
1138    Jan
1139    Feb
1140    Mar
1141    Apr
1142    May
1143    Jun
1144    Jul
1145    Aug
1146    Sep
1147    Oct
1148    Nov
1149    Dec
1150    Jan
1151    Feb
1152    Mar
1153    Apr
1154    May
1155    Jun
1156    Jul
1157    Aug
1158    Sep
1159    Oct
1160    Nov
1161    Dec
1162    Jan
1163    Feb
1164    Mar
1165    Apr
1166    May
1167    Jun
1168    Jul
1169    Aug
1170    Sep
1171    Oct
1172    Nov
1173    Dec
1174    Jan
1175    Feb
1176    Mar
1177    Apr
1178    May
1179    Jun
1180    Jul
1181    Aug
1182    Sep
1183    Oct
1184    Nov
1185    Dec
1186    Jan
1187    Feb
1188    Mar
1189    Apr
1190    May
1191    Jun
1192    Jul
1193    Aug
1194    Sep
1195    Oct
1196    Nov
1197    Dec
1198    Jan
1199    Feb
1200    Mar
1201    Apr
1202    May
1203    Jun
1204    Jul
1205    Aug
1206    Sep
1207    Oct
1208    Nov
1209    Dec
1210    Jan
1211    Feb
1212    Mar
1213    Apr
1214    May
1215    Jun
1216    Jul
1217    Aug
1218    Sep
1219    Oct
1220    Nov
1221    Dec
1222    Jan
1223    Feb
1224    Mar
1225    Apr
1226    May
1227    Jun
1228    Jul
1229    Aug
1230    Sep
1231    Oct
1232    Nov
1233    Dec
1234    Jan
1235    Feb
1236    Mar
1237    Apr
1238    May
1239    Jun
1240    Jul
1241    Aug
1242    Sep
1243    Oct
1244    Nov
1245    Dec
1246    Jan
1247    Feb
1248    Mar
1249    Apr
1250    May
1251    Jun
1252    Jul
1253    Aug
1254    Sep
1255    Oct
1256    Nov
1257    Dec
1258    Jan
1259    Feb
1260    Mar
1261    Apr
1262    May
1263    Jun
1264    Jul
1265    Aug
1266    Sep
1267    Oct
1268    Nov
1269    Dec
1270    Jan
1271    Feb
1272    Mar
1273    Apr
1274    May
1275    Jun
1276    Jul
1277    Aug
1278    Sep
1279    Oct
1280    Nov
1281    Dec
1282    Jan
1283    Feb
1284    Mar
1285    Apr
1286    May
1287    Jun
1288    Jul
1289    Aug
1290    Sep
1291    Oct
1292    Nov
1293    Dec
1294    Jan
1295    Feb
1296    Mar
1297    Apr
1298    May
1299    Jun
1300    Jul
1301    Aug
1302    Sep
1303    Oct
1304    Nov
1305    Dec
1306    Jan
1307    Feb
1308    Mar
1309    Apr
1310    May
1311    Jun
1312    Jul
1313    Aug
1314    Sep
1315    Oct
1316    Nov
1317    Dec
1318    Jan
1319    Feb
1320    Mar
1321    Apr
1322    May
1323    Jun
1324    Jul
1325    Aug
1326    Sep
1327    Oct
1328    Nov
1329    Dec
1330    Jan
1331    Feb
1332    Mar
1333    Apr
1334    May
1335    Jun
1336    Jul
1337    Aug
1338    Sep
1339    Oct
1340    Nov
1341    Dec
1342    Jan
1343    Feb
1344    Mar
1345    Apr
1346    May
1347    Jun
1348    Jul
1349    Aug
1350    Sep
1351    Oct
1352    Nov
1353    Dec
1354    Jan
1355    Feb
1356    Mar
1357    Apr
1358    May
1359    Jun
1360    Jul
1361    Aug
1362    Sep
1363    Oct
1364    Nov
1365    Dec
1366    Jan
1367    Feb
1368    Mar
1369    Apr
1370    May
1371    Jun
1372    Jul
1373    Aug
1374    Sep
1375    Oct
1376    Nov
1377    Dec
1378    Jan
1379    Feb
1380    Mar
1381    Apr
1382    May
1383    Jun
1384    Jul
1385    Aug
1386    Sep
1387    Oct
1388    Nov
1389    Dec
1390    Jan
1391    Feb
1392    Mar
1393    Apr
1394    May
1395    Jun
1396    Jul
1397    Aug
1398    Sep
1399    Oct
1400    Nov
1401    Dec
1402    Jan
1403    Feb
1404    Mar
1405    Apr
1406    May
1407    Jun
1408    Jul
1409    Aug
1410    Sep
1411    Oct
1412    Nov
1413    Dec
1414    Jan
1415    Feb
1416    Mar
1417    Apr
1418    May
1419    Jun
1420    Jul
1421    Aug
1422    Sep
1423    Oct
1424    Nov
1425    Dec
1426    Jan
1427    Feb
1428    Mar
1429    Apr
1430    May
1431    Jun
1432    Jul
1433    Aug
1434    Sep
1435    Oct
1436    Nov
1437    Dec
1438    Jan
1439    Feb
1440    Mar
1441    Apr
1442    May
1443    Jun
1444    Jul
1445    Aug
1446    Sep
1447    Oct
1448    Nov
1449    Dec
1450    Jan
1451    Feb
1452    Mar
1453    Apr
1454    May
1455    Jun
1456    Jul
1457    Aug
1458    Sep
1459    Oct
1460    Nov
1461    Dec
1462    Jan
1463    Feb
1464    Mar
1465    Apr
1466    May
1467    Jun
1468    Jul
1469    Aug
1470    Sep
1471    Oct
1472    Nov
1473    Dec
1474    Jan
1475    Feb
1476    Mar
1477    Apr
1478    May
1479    Jun
1480    Jul
1481    Aug
1482    Sep
1483    Oct
1484    Nov
1485    Dec
1486    Jan
1487    Feb
1488    Mar
1489    Apr
1490    May
1491    Jun
1492    Jul
1493    Aug
1494    Sep
1495    Oct
1496    Nov
1497    Dec
1498    Jan
1499    Feb
1500    Mar
1501    Apr
1502    May
1503    Jun
1504    Jul
1505    Aug
1506    Sep
1507    Oct
1508    Nov
1509    Dec
1510    Jan
1511    Feb
1512    Mar
1513    Apr
1514    May
1515    Jun
1516    Jul
1517    Aug
1518    Sep
1519    Oct
1520    Nov
1521    Dec
1522    Jan
1523    Feb
1524    Mar
1525    Apr
1526    May
1527    Jun
1528    Jul
1529    Aug
1530    Sep
1531    Oct
1532    Nov
1533    Dec
1534    Jan
1535    Feb
1536    Mar
1537    Apr
1538    May
1539    Jun
1540    Jul
1541    Aug
1542    Sep
1543    Oct
1544    Nov
1545    Dec
1546    Jan
1547    Feb
1548    Mar
1549    Apr
1550    May
1551    Jun
1552    Jul
1553    Aug
1554    Sep
1555    Oct
1556    Nov
1557    Dec
1558    Jan
1559    Feb
1560    Mar
1561    Apr
1562    May
1563    Jun
1564    Jul
1565    Aug
1566    Sep
1567    Oct
1568    Nov
1569    Dec
1570    Jan
1571    Feb
1572    Mar
1573    Apr
1574    May
1575    Jun
1576    Jul
1577    Aug
1578    Sep
1579    Oct
1580    Nov
1581    Dec
1582    Jan
1583    Feb
1584    Mar
1585    Apr
1586    May
1587    Jun
1588    Jul
1589    Aug
1590    Sep
1591    Oct
1592    Nov
1593    Dec
1594    Jan
1595    Feb
1596    Mar
1597    Apr
1598    May
1599    Jun
1600    Jul
1601    Aug
1602    Sep
1603    Oct
1604    Nov
1605    Dec
1606    Jan
1607    Feb
1608    Mar
1609    Apr
1610    May
1611    Jun
1612    Jul
1613    Aug
1614    Sep
1615    Oct
1616    Nov
1617    Dec
1618    Jan
1619    Feb
1620    Mar
1621    Apr
1622    May
1623    Jun
1624    Jul
1625    Aug
1626    Sep
1627    Oct
1628    Nov
1629    Dec
1630    Jan
1631    Feb
1632    Mar
1633    Apr
1634    May
1635    Jun
1636    Jul
1637    Aug
1638    Sep
1639    Oct
1640    Nov
1641    Dec
1642    Jan
1643    Feb
1644    Mar
1645    Apr
1646    May
1647    Jun
1648    Jul
1649    Aug
1650    Sep
1651    Oct
1652    Nov
1653    Dec
1654    Jan
1655    Feb
1656    Mar
1657    Apr
1661    May
1662    Jun
1663    Jul
1664    Aug
1665    Sep
1666    Oct
1667    Nov
1668    Dec
1669    Jan
1670    Feb
1671    Mar
1672    Apr
1673    May
1674    Jun
1675    Jul
1676    Aug
1677    Sep
1678    Oct

In [39]:
pd.reset_option('display.max_rows')

In [40]:
df['Month'].unique()

['Jan', 'Feb', 'Mar', 'Apr', 'May', ..., 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
Length: 12
Categories (12, string): [Apr, Aug, Dec, Feb, ..., May, Nov, Oct, Sep]

In [41]:
valid_month=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
       'Oct', 'Nov', 'Dec']

In [42]:
df.loc[~df['Month'].isin(valid_month), 'Month']=np.nan
df['Month'].sample(10)

5905    Oct
1344    Mar
5523    Mar
1387    Oct
5265    Sep
4322    Feb
196     Oct
3465    Sep
3559    Jul
3024    Dec
Name: Month, dtype: category
Categories (12, string): [Apr, Aug, Dec, Feb, ..., May, Nov, Oct, Sep]

# 4> Genre

In [43]:
df['Genre'].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)

In [44]:
# array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
#        'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
#        'Strategy'], dtype=object)

#  genre object o - c = Role-Playing -> Role Playing

df['Genre']=(df['Genre']
             .astype('string')
             .str.strip()
             .str.lower()
             .str.replace('-', ' ', regex=True)
             .replace(r'^\s*$', np.nan, regex=True)
             .str.title()
             .astype('category')
            )

# ['Sports', 'Platform', 'Racing', 'Role Playing', 'Puzzle', ..., 'Simulation', 'Action', 'Fighting', 'Adventure', 'Strategy']
# Length: 12
# Categories (12, string): [Action, Adventure, Fighting, Misc, ..., Shooter, Simulation, Sports, Strategy]


# valid_gerne=['Sports', 'Platform', 'Racing', 'Role Playing', 'Puzzle', 'Misc',
#        'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
#        'Strategy']

# df.loc[~df['Genre'].isin(valid_gerne), 'Genre']=np.nan

df['Genre'].sample(15)

801         Sports
1225        Sports
4404      Strategy
5374      Platform
4920        Sports
651         Racing
125        Shooter
2884        Racing
5481    Simulation
1330      Strategy
2529        Action
1788          Misc
5447     Adventure
2273     Adventure
5669     Adventure
Name: Genre, dtype: category
Categories (12, string): [Action, Adventure, Fighting, Misc, ..., Shooter, Simulation, Sports, Strategy]

In [45]:
df['Genre'].unique()

['Sports', 'Platform', 'Racing', 'Role Playing', 'Puzzle', ..., 'Simulation', 'Action', 'Fighting', 'Adventure', 'Strategy']
Length: 12
Categories (12, string): [Action, Adventure, Fighting, Misc, ..., Shooter, Simulation, Sports, Strategy]

In [46]:
valid_gerne=['Sports', 'Platform', 'Racing', 'Role Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy']

In [47]:
df.loc[~df['Genre'].isin(valid_gerne), 'Genre']=np.nan

df['Genre'].sample(15)

121        Shooter
3195          Misc
1751        Puzzle
3545        Action
3833          Misc
5833    Simulation
3473        Sports
1090    Simulation
5006        Action
4937      Strategy
4841        Sports
1502      Fighting
4269      Platform
5316      Platform
3066        Sports
Name: Genre, dtype: category
Categories (12, string): [Action, Adventure, Fighting, Misc, ..., Shooter, Simulation, Sports, Strategy]

# 5> Publisher object - [-.,] [N/A, Unknown]

In [48]:
df['Publisher'].unique()

array(['Nintendo', 'Microsoft Game Studios', 'Take-Two Interactive',
       'Sony Computer Entertainment', 'Activision', 'Ubisoft',
       'Bethesda Softworks', 'Electronic Arts', 'Sega', 'SquareSoft',
       'Atari', '505 Games', 'Capcom', 'GT Interactive',
       'Konami Digital Entertainment',
       'Sony Computer Entertainment Europe', 'Square Enix', 'LucasArts',
       'Virgin Interactive', 'Warner Bros. Interactive Entertainment',
       'Universal Interactive', 'Eidos Interactive', 'RedOctane',
       'Vivendi Games', 'Enix Corporation', 'Namco Bandai Games',
       'Palcom', 'Hasbro Interactive', 'THQ', 'Fox Interactive',
       'Acclaim Entertainment', 'MTV Games', 'Disney Interactive Studios',
       nan, 'Majesco Entertainment', 'Codemasters', 'Red Orb', 'Level 5',
       'Arena Entertainment', 'Midway Games', 'JVC', 'Deep Silver',
       '989 Studios', 'NCSoft', 'UEP Systems', 'Parker Bros.', 'Maxis',
       'Imagic', 'Tecmo Koei', 'Valve Software', 'ASCII Entertainment',
       'Mindscape', 'Infogrames', 'Unknown', 'Square', 'Valve',
       'Activision Value', 'Banpresto', 'D3Publisher',
       'Oxygen Interactive', 'Red Storm Entertainment', 'Video System',
       'Hello Games', 'Global Star', 'Gotham Games', 'Westwood Studios',
       'GungHo', 'Crave Entertainment', 'Hudson Soft', 'Coleco',
       'Rising Star Games', 'Atlus', 'TDK Mediactive', 'ASC Games',
       'Zoo Games', 'Accolade', 'Sony Online Entertainment', '3DO', 'RTL',
       'Natsume', 'Focus Home Interactive', 'Alchemist',
       'Black Label Games', 'SouthPeak Games', 'Mastertronic', 'Ocean',
       'Zoo Digital Publishing', 'Psygnosis', 'City Interactive',
       'Empire Interactive', 'Success', 'Compile', 'Russel', 'Taito',
       'Agetec', 'GSP', 'Microprose', 'Play It', 'Slightly Mad Studios',
       'Tomy Corporation', 'Sammy Corporation', 'Koch Media',
       'Game Factory', 'Titus', 'Marvelous Entertainment', 'Genki',
       'Mojang', 'Pinnacle', 'CTO SpA', 'TalonSoft', 'Crystal Dynamics',
       'SCi', 'Quelle', 'mixi, Inc', 'Rage Software', 'Ubisoft Annecy',
       'Scholastic Inc.', 'Interplay', 'Mystique', 'ChunSoft',
       'Square EA', '20th Century Fox Video Games', 'Avanquest Software',
       'Hudson Entertainment', 'Nordic Games', 'Men-A-Vision', 'Nobilis',
       'Big Ben Interactive', 'Touchstone', 'Spike', 'Jester Interactive',
       'Nippon Ichi Software', 'LEGO Media', 'Quest',
       'Illusion Softworks', 'Tigervision', 'Funbox Media',
       'Rocket Company', 'Metro 3D', 'Mattel Interactive', 'IE Institute',
       'Rondomedia', 'Sony Computer Entertainment America',
       'Universal Gamex', 'Ghostlight', 'Wizard Video Games',
       'BMG Interactive Entertainment', 'PQube', 'Trion Worlds', 'Laguna',
       'Ignition Entertainment', 'Takara', 'Kadokawa Shoten', 'Destineer',
       'Enterbrain', 'Xseed Games', 'Imagineer',
       'System 3 Arcade Software', 'CPG Products', 'Aruze Corp',
       'Gamebridge', 'Midas Interactive Entertainment', 'Jaleco',
       'Answer Software', 'XS Games', 'Activision Blizzard',
       'Pack In Soft', 'Rebellion', 'Xplosiv', 'Ultravision',
       'GameMill Entertainment', 'Wanadoo', 'NovaLogic', 'Telltale Games',
       'Epoch', 'BAM! Entertainment', 'Knowledge Adventure', 'Mastiff',
       'Tetris Online', 'Harmonix Music Systems', 'ESP', 'TYO',
       'Telegames', 'Mud Duck Productions', 'Screenlife', 'Pioneer LDC',
       'Magical Company', 'Mentor Interactive', 'Kemco',
       'Human Entertainment', 'Avanquest', 'Data Age',
       'Electronic Arts Victor', 'Black Bean Games', 'Jack of All Games',
       '989 Sports', 'Takara Tomy', 'Media Rings', 'Elf', 'Kalypso Media',
       'Starfish', 'Zushi Games', 'Jorudan', 'Destination Software, Inc',
       'New', 'Brash Entertainment', 'ITT Family Games', 'PopCap Games',
       'Home Entertainment Suppliers', 'Ackkstudios', 'Starpath Corp.',
       'P2 Games', 'BPS', 'Gathering of Developers', 'NewKidCo',
       'Storm City Games', 'CokeM Interactive', 'CBS Electronics',
       'Magix', 'Marvelous Interactive'], dtype=object)

In [49]:

df['Publisher']=(df['Publisher']
                .astype('string')
                 .str.strip()
                 .str.lower()
                 .replace(r'[^a-zA-A0-9\s]', ' ', regex=True)
                 .replace(r'\s+', ' ', regex=True)
                 .replace(r'^\s*$', np.nan,regex=True)
                 .replace(['n/a','unknown'], np.nan)
                 .str.strip()
                 .str.title()
                 .astype('category')
                )

df['Publisher'].sample(10)

4950           Sony Computer Entertainment
865                               Nintendo
649           Konami Digital Entertainment
4166                          Midway Games
1239                                  Sega
2838                               Ubisoft
1603                                 Atari
2729                       Electronic Arts
1960                       Electronic Arts
723     Sony Computer Entertainment Europe
Name: Publisher, dtype: category
Categories (218, string): [20Th Century Fox Video Games, 3Do, 505 Games, 989 Sports, ..., Xseed Games, Zoo Digital Publishing, Zoo Games, Zushi Games]

In [50]:
df['Publisher'].unique()

['Nintendo', 'Microsoft Game Studios', 'Take Two Interactive', 'Sony Computer Entertainment', 'Activision', ..., 'Storm City Games', 'Cokem Interactive', 'Cbs Electronics', 'Magix', 'Marvelous Interactive']
Length: 219
Categories (218, string): [20Th Century Fox Video Games, 3Do, 505 Games, 989 Sports, ..., Xseed Games, Zoo Digital Publishing, Zoo Games, Zushi Games]

# Country

In [51]:
df['Country'].unique()

array(['United States', 'USA', 'Australia'], dtype=object)

In [52]:
# Here i am we have 3 countries like USA, United States, Australia so replace United States make as USA

df['Country']=(df['Country']
               .astype('string')
               .str.strip()
               .replace({'United States':'USA'}, regex=True)
               .str.strip()
               .replace(r'^\s*$',np.nan, regex=True)
               .astype('category')
)
df['Country'].sample(30)

3218    Australia
5337    Australia
4763    Australia
3938    Australia
1313          USA
831           USA
2872    Australia
5067    Australia
2251          USA
5518    Australia
4777    Australia
3004    Australia
2124          USA
886           USA
893           USA
4471    Australia
3530    Australia
5365    Australia
4588    Australia
4637    Australia
4750    Australia
1860          USA
3678    Australia
2322          USA
309           USA
5853    Australia
2341          USA
2506          USA
1391          USA
334           USA
Name: Country, dtype: category
Categories (2, string): [Australia, USA]

In [53]:
df['Country'].unique()

['USA', 'Australia']
Categories (2, string): [Australia, USA]

In [54]:
valid_country=['USA','Australia']

In [55]:
df.loc[~df['Country'].isin(valid_country), 'Country']=np.nan
df['Country'].sample(30)

1792          USA
2291          USA
1983          USA
2524          USA
3488    Australia
1557          USA
2955    Australia
4259    Australia
2790          USA
2288          USA
2013          USA
4315    Australia
89            USA
1555          USA
4469    Australia
5149    Australia
1468          USA
1406          USA
4780    Australia
3061    Australia
2554          USA
3439    Australia
2310          USA
4332    Australia
591           USA
2064          USA
1194          USA
5433    Australia
80            USA
4267    Australia
Name: Country, dtype: category
Categories (2, string): [Australia, USA]

# City

In [56]:
df['City'].unique()

array(['Fairfield', 'Edmonds', 'Louisville', 'Round Rock', 'Nashville',
       'Newark', 'Fremont', 'Odessa', 'Dallas', 'Los Angeles',
       'New Bedford', 'Little Rock', 'Lafayette', 'New York City',
       'San Francisco', 'Milwaukee', 'Oceanside', 'Tulsa', 'Inglewood',
       'San Diego', 'Skokie', 'Lawrence', 'Philadelphia', 'Jackson',
       'Stockton', 'Houston', 'Cincinnati', 'Phoenix', 'Richmond',
       'Madison', 'Toledo', 'Seattle', 'Chicago', 'Thornton',
       'Charlottesville', 'Tampa', 'Denver', 'El Paso', 'Chattanooga',
       'Baltimore', 'Asheville', 'Atlanta', 'Columbus', 'Rockford',
       'Charlotte', 'Westminster', 'Carrollton', 'San Antonio',
       'Homestead', 'Long Beach', 'Miramar', 'Hillsboro', 'Hagerstown',
       'Roseville', 'Bowling Green', 'Pasadena', 'Springfield',
       'Glendale', 'Garland', 'Tucson', 'Pasco', 'Brentwood',
       'Fayetteville', 'Farmington', 'Greenwood', 'Eagan', 'Wilmington',
       'Orlando', 'Henderson', 'Saint Louis', 'Bellingham', 'Everett',
       'Tallahassee', 'Austin', 'Cranston', 'Redmond', 'Yuma',
       'Thousand Oaks', 'Sacramento', 'Lakewood', 'Aurora', 'Belleville',
       'Chico', 'Knoxville', 'Mentor', 'Bakersfield', 'Marion', 'Lodi',
       'Sandy Springs', 'Fort Collins', 'Clovis', 'Woonsocket',
       'Georgetown', 'Cleveland', 'Arlington', 'Hialeah', 'Draper',
       'Providence', 'Coppell', 'Apple Valley', 'Akron', 'Oakland',
       'Palm Coast', 'Tempe', 'Port Saint Lucie', 'Lakeville',
       'Watertown', 'Columbia', 'Plainfield', 'Lake Forest',
       'Jacksonville', 'Concord', 'Sioux Falls', 'Suffolk', 'Manchester',
       'Kent', 'Burlington', 'Indianapolis', 'Mount Vernon', 'Detroit',
       'Miami', 'Wheeling', 'Parma', 'Carlsbad', 'Peoria',
       'Pembroke Pines', 'Lorain', 'Dublin', 'Tigard', 'Omaha', 'Auburn',
       'Fargo', 'Las Vegas', 'Boynton Beach', 'Lancaster', 'York',
       'Roswell', 'Florence', 'Oklahoma City', 'Dearborn', 'Fresno',
       'Tyler', 'Albuquerque', 'Raleigh', 'Anaheim', 'Troy', 'Decatur',
       'Minneapolis', 'Wichita', 'Great Falls', 'Waterbury', 'Washington',
       'Huntsville', 'Reno', 'Moreno Valley', 'Tamarac', 'Greenville',
       'Hempstead', 'Franklin', 'San Jose', 'Oxnard', 'Des Moines',
       'Edmond', 'Niagara Falls', 'The Colony', 'Vancouver',
       'Thomasville', 'Mesa', 'La Porte', 'Chula Vista', 'Urbandale',
       'Portland', 'Hollywood', 'Laredo', 'Mobile', 'Covington',
       'La Crosse', 'Broken Arrow', 'Arvada', 'Bristol', 'Monroe',
       'Johnson City', 'Huntington Beach', 'Athens', 'Pharr',
       'Costa Mesa', 'Perth Amboy', 'Provo', 'Paterson', 'Fort Worth',
       'Delray Beach', 'Passaic', 'Vallejo', 'Middletown',
       'Colorado Springs', 'Hesperia', 'San Clemente', 'Rome', 'Milford',
       'Sierra Vista', 'Pocatello', 'Memphis', 'Harlingen', 'Clinton',
       'Smyrna', 'Independence', 'Parker', 'Sunnyvale', 'Plano',
       'Fort Lauderdale', 'North Charleston', 'Saginaw', 'Gladstone',
       'Canton', 'Yonkers', 'Grove City', 'Modesto', 'Coachella', 'Bryan',
       'Virginia Beach', 'Rochester', 'Lawton', 'Woodland', 'Durham',
       'Freeport', 'Chandler', 'Montgomery', 'Santa Ana', 'Quincy',
       'Lake Charles', 'Murray', 'Salem', 'Lowell', 'Chapel Hill',
       'Hickory', 'Laurel', 'Harrisonburg', 'Westfield', 'Texarkana',
       'Coral Springs', 'Sanford', 'Orange', 'Santa Barbara', 'Hoover',
       'Southaven', 'Cuyahoga Falls', 'Waco', 'Muskogee', 'Gilbert',
       'Woodstock', 'Riverside', 'Bellevue', 'Taylor', 'Cheyenne',
       'Marysville', 'Sterling Heights', 'Lansing', 'Trenton', 'El Cajon',
       'Appleton', 'Greensboro', 'Spokane', 'Grand Rapids',
       'New Rochelle', 'Waukesha', 'Sheboygan', 'Edinburg', 'Kenner',
       'Lakeland', 'Amarillo', 'Hattiesburg', 'Highland Park', 'Salinas',
       'Superior', 'Sparks', 'Mission Viejo', 'Encinitas', 'Scottsdale',
       'Alexandria', 'Wilson', 'Evanston', 'Saint Peters', 'Redwood City',
       'Andover', 'Mishawaka', 'Atlantic City', 'Morristown', 'Loveland',
       'Meridian', 'Chesapeake', 'Palatine', 'Abilene', 'North Las Vegas',
       'Grand Prairie', 'Summerville', 'San Angelo', 'Naperville',
       'Utica', 'Longview', 'Overland Park', 'Danville', 'Bloomington',
       'Chester', 'Melbourne', 'Saint Charles', 'Meriden', 'Bedford',
       'Bolingbrook', 'Saint Petersburg', 'Missouri City', 'Jonesboro',
       'Gulfport', 'Vineland', 'Rancho Cucamonga', 'Newport News',
       'Beaumont', 'Reading', 'Rogers', 'Torrance', 'Lincoln Park',
       'East Orange', 'Warner Robins', 'Bridgeton', 'Pueblo',
       'Cedar Rapids', 'Redondo Beach', 'Gresham', 'Bethlehem',
       'Westland', 'Irving', 'Dover', 'Gastonia', 'Waynesboro',
       'Hendersonville', 'Tuscaloosa', 'Oak Park', 'Garden City',
       'Escondido', 'Jupiter', 'Buffalo', 'Deltona', 'League City',
       'Pine Bluff', 'La Mesa', 'Salt Lake City', 'Waterloo',
       'Citrus Heights', 'Pomona', 'Olympia', 'Norwich', 'Frisco',
       'Mcallen', 'Pompano Beach', 'Cambridge', 'Dearborn Heights',
       'West Palm Beach', 'Goldsboro', 'Rockville', 'Eugene',
       'San Luis Obispo', 'Adelaide', 'Sydney', 'Perth', 'Bundaberg',
       'Brisbane', 'Wagga Wagga', 'Gold Coast', 'Maitland', 'Wollongong',
       'Hobart', 'Bunbury', 'Central Coast', 'Bowral - Mittagong',
       'Busselton', 'Bathurst', 'Cessnock', 'Kurri Kurri', 'Canberra',
       'Burnie - Somerset', 'Newcastle', 'Cairns', 'Townsville',
       'Charters Towers', 'Darwin', 'Kempsey', 'Crafers - Bridgewater',
       'Sunshine Coast', 'Ballarat', 'Rockhampton', 'Devonport', 'Mackay'],
      dtype=object)

In [57]:
df['City']=(df['City']
            .astype('string')
            .str.strip()
            .str.lower()
            .str.replace('-',' ', regex=True)
            .str.replace(r'\s+', ' ', regex=True)
            .str.strip()
            .str.title()
            .replace({'Mcallen':'McAllen'})
            .replace(r'^\s*$', np.nan, regex=True)
            .astype('category')
            
           )
df['City'].sample(40)

4159              Sydney
495               Oxnard
4401              Sydney
750        New York City
564       Pembroke Pines
3787              Sydney
2418        Philadelphia
5461              Sydney
2533         Tallahassee
474               Lorain
4069              Sydney
337               Dublin
4234              Sydney
5236              Sydney
4508              Sydney
248              Seattle
2111             Houston
5386              Sydney
4408              Sydney
737         Philadelphia
4896              Sydney
4769              Sydney
438        San Francisco
156        New York City
78         New York City
1085             Phoenix
5591              Sydney
1107           Arlington
4059              Sydney
1457               Salem
5227              Sydney
196              Houston
397        Oklahoma City
2683    Dearborn Heights
2878           Melbourne
744         Philadelphia
1982             Seattle
713              Milford
3290              Sydney
2609             Houston
Name: City, dtype: category
Categories (391, string): [Abilene, Adelaide, Akron, Albuquerque, ..., Woonsocket, Yonkers, York, Yuma]

# State

In [58]:
df['State'].unique()

array(['California', 'Washington', 'Kentucky', 'Texas', 'Tennessee',
       'Ohio', 'Nebraska', 'Massachusetts', 'Arkansas', 'Indiana',
       'New York', 'Wisconsin', 'Oklahoma', 'Illinois', 'Pennsylvania',
       'Mississippi', 'Arizona', 'Colorado', 'Virginia', 'Florida',
       'Maryland', 'North Carolina', 'Georgia', 'Oregon', 'New Mexico',
       'Minnesota', 'Missouri', 'Rhode Island', 'Connecticut',
       'New Jersey', 'Utah', 'Michigan', 'South Dakota', 'Delaware',
       'New Hampshire', 'West Virginia', 'North Dakota', 'Nevada',
       'South Carolina', 'Louisiana', 'Kansas', 'Montana', 'Vermont',
       'District of Columbia', 'Alabama', 'Iowa', 'Idaho', 'Wyoming',
       'South Australia', 'Victoria', 'New South Wales',
       'Western Australia', 'Queensland', 'Tasmania',
       'Australian Capital Territory', 'Northern Territory'], dtype=object)

In [59]:
df['State']=(df['State']
            .astype('string')
            .str.strip()
            .str.title()
            .replace(r'^\s*$',np.nan, regex=True)
            .astype('category')
            )
df['State'].sample(50)

4087         New South Wales
3154         New South Wales
1875            Pennsylvania
2168                New York
1383              California
5873         New South Wales
2200    District Of Columbia
3773         New South Wales
1294              California
2176            Pennsylvania
2740              California
763                 Illinois
5498         New South Wales
4450         New South Wales
1108                Colorado
4573         New South Wales
1676          North Carolina
5254         New South Wales
1810                Illinois
2907              Queensland
3532         New South Wales
1618                    Ohio
2575            Pennsylvania
1970              California
4513         New South Wales
4126         New South Wales
1742                New York
1928              Washington
5357         New South Wales
2149            Pennsylvania
4433         New South Wales
114                    Texas
5259         New South Wales
213               California
1055                New York
2550              Washington
147               California
999                Wisconsin
4354         New South Wales
3510         New South Wales
116               California
4301         New South Wales
3927         New South Wales
3394         New South Wales
3                      Texas
279              Connecticut
398             Pennsylvania
3823         New South Wales
1722              Washington
5592         New South Wales
Name: State, dtype: category
Categories (56, string): [Alabama, Arizona, Arkansas, Australian Capital Territory, ..., West Virginia, Western Australia, Wisconsin, Wyoming]

# Region

In [60]:
df['Region'].unique()

array(['West', 'South', 'Central', 'East', nan, 'Other', 'North'],
      dtype=object)

In [61]:
df['Region']=(df['Region']
              .astype('string')
              .str.strip()
              .str.lower()
              .replace({'nan':np.nan},regex=True)
              .replace(r'^\s*$', np.nan, regex=True)
              .str.title()
              .astype('category')

)
df['Region'].sample(50)

223        West
1104       East
2552      South
1517       East
4242       West
2966      South
1151    Central
5758       West
1490    Central
2739       West
4843       West
178       South
945        East
1353       West
4490       West
4144       West
2597       East
1896       West
813        East
4614       West
4379       West
3286       West
4947       West
4676       West
5255       West
126        <NA>
2943      Other
444        West
3671       West
1519       West
754        West
956        West
2260       West
2732      South
5122       West
5148       West
5456       West
2223       East
284        East
1240       East
619       South
4217       West
4464       West
3322       West
4543       West
2954      Other
2259       East
3070       West
3965       West
1280       East
Name: Region, dtype: category
Categories (6, string): [Central, East, North, Other, South, West]

In [62]:
df['Region'].unique()

['West', 'South', 'Central', 'East', <NA>, 'Other', 'North']
Categories (6, string): [Central, East, North, Other, South, West]

# NA_Sales

In [63]:
df['NA_Sales'].unique()

array(['$41.49', '$29.08', '$15.85', '$15.75', '$11.27', '$23.20',
       '$11.38', '$14.03', '$14.59', '$26.93', '$9.07', '$9.81', '9',
       '8.94', '9.09', '14.97', '7.01', '9.43', '12.78', '4.75', '6.42',
       '10.83', '9.54', '9.63', '8.41', '6.06', '5.57', '3.44', '6.85',
       '9.03', '5.89', '9.67', '5.17', '5.77', '4.99', '8.25', '8.52',
       '5.54', '6.99', '6.75', '5.98', '2.55', '4.74', '7.97', '3.8',
       '4.4', '6.91', '3.01', '6.16', '4.23', '6.76', '4.02', '4.89',
       '2.96', '4.76', '5.99', '4.34', '5.08', '6.05', '6.72', '7.03',
       '5.55', '3.66', '6.63', '4.09', '5.84', '3.88', '5.91', '4.36',
       '5.58', '2.01', '4.46', '5.03', '3.54', '1.11', '1.79', '6.82',
       '3.81', '2.91', '1.06', '0.98', '5.8', '2.58', '2.28', '2.82',
       '7.28', '2.9', '2.93', '2.8', '4.1', '3.78', '5.39', '3.24',
       '4.79', '3.83', '4.52', '3.51', '2.85', '3.27', '3.68', '4.41',
       '3.13', '2.47', '4.12', '4.14', '0.78', '2.71', '2.77', '3.23',
       '3.5', '4.15', '3.1', '0.84', '1.67', '2.79', '0.79', '3.25',
       '3.74', '2.64', '4.98', '2.57', '3.64', '3.7', '4.01', '0.07',
       '3.11', '3.92', '4.05', '2.45', '4.47', '2.63', '3.18', '2.41',
       '1.88', '0.66', '2.26', '2.49', '2.97', '2.54', '2.95', '3.28',
       '2.7', '2.99', '0.47', '3.14', '2.62', '3.21', '2.72', '2.07',
       '1.97', '1.74', '2.18', '3.02', '1.62', '1.92', '3.33', '1.22',
       '2.3', '4.26', '0.65', '2.43', '2.32', '1.08', '1.9', '2.1',
       '0.96', '1.64', '1.98', '3.59', '3.22', '1.96', '2.66', '1.7',
       '0.6', '3.4', '2.05', '3.42', '2.59', '3.36', '3.06', '3.49',
       '3.39', '1.85', '2.31', '3.98', '2.89', '0', '2.74', '2.56',
       '1.91', '0.57', '0.28', '2.36', '1.73', '3.05', '1.87', '1.94',
       '2.08', '2.29', '2.42', '2.6', '1.89', '1.78', '1.55', '3.19',
       '4.18', '4.21', '3.63', '0.2', '1.54', '2.67', '0.1', '2.19',
       '2.03', '3.03', '2.2', '0.92', '2.75', '4', '2.51', '2.11', '2.23',
       '1.41', '3', '1.46', '0.88', '1.3', '1.28', '2.25', '2.02', '3.38',
       '2.04', '3.79', '1.4', '4.03', '1.65', '0.71', '2.14', '1.42',
       '2.13', '2.65', '2.35', '0.12', '1.68', '1.12', '2.78', '1.38',
       '2.15', '1.18', '1.33', '0.67', '1.53', '1.15', '0.93', '2.12',
       '2.48', '0.16', '0.87', '2.21', '1.44', '1.49', '1.14', '2.4',
       '1.82', '1.37', '1.93', '0.58', '1.59', '2.53', '2.33', '0.05',
       '1.61', '2.38', '1.57', '1.56', '1.23', '1.66', '1.17', '2.84',
       '0.59', '2.09', '2.39', '1.34', '1.13', '0.86', '1.75', '0.46',
       '1.43', '1.63', '1.45', '1.47', '1.99', '1.5', '0.8', '1.36',
       '0.5', '0.25', '0.95', '1.27', '0.03', '1.72', '0.73', '1.76',
       '1.35', '1.48', '1.52', '1.86', '2.06', '0.68', '0.91', '1.69',
       '0.08', '1.29', '2.17', '2.5', '1.01', '1.58', '1.04', '2.22',
       '1.83', '0.61', '1.84', '0.99', '1.51', '0.09', '0.4', '2.52',
       '1.32', '0.02', '1.05', '0.29', '1.19', '0.89', '0.3', '1.2',
       '1.24', '1.25', '1.07', '1.02', '0.69', '1.95', '2', '0.76',
       '0.63', '0.9', '0.48', '0.64', '0.37', '1.31', '0.15', '1.21',
       '0.49', '0.13', '1.81', '1.26', '0.81', '0.77', '1', '1.16',
       '1.39', '0.85', '0.52', '0.51', '0.38', '0.62', '1.09', '1.71',
       '1.03', '0.34', '1.6', '0.54', '0.14', '0.01', '0.82', '0.83',
       '0.11', '0.94', '1.77', '0.7', '0.97', '0.75', '0.35', '0.72',
       '0.74', '0.18', '1.1', '0.56', '0.26', '0.21', '0.22', '0.53',
       '0.55', '0.23', '0.39', '0.32', '0.45', '0.41', '0.31', '0.24',
       '0.06', '0.43', '0.44', '0.19', '0.04', '0.17', '0.36', '0.33',
       '0.27', '0.42', '$0.09', '$0.18', '$0.12', '$0.10', '$0.00',
       '$0.24', '$0.29', '$0.17', '$0.25', '$0.28', '$0.22'], dtype=object)

In [64]:
df['NA_Sales'].sample(50)

1868      0.44
1666      0.78
4487      0.34
2327      0.42
2367      0.44
1137       0.6
2274      0.16
286       3.36
1697      0.49
1885      0.24
1813       0.7
4797      0.38
2321      0.27
4732      0.24
1784         0
3610      0.34
5112      0.34
4878      0.19
4627         0
3253      0.35
2926      0.54
4845      0.22
5442      0.17
1958         0
2983      0.34
3670         0
1578         0
2402      0.48
2579      0.62
4416      0.22
2551      0.45
4491      0.31
2162      0.38
8       $14.59
4960      0.24
2549      0.06
5838      0.22
1252      0.65
1661      0.59
2858      0.23
3915      0.28
1833      0.63
1594      0.49
2140      0.37
1814      1.01
178       3.02
1908      0.53
2174      0.47
2137      0.88
3868         0
Name: NA_Sales, dtype: object

In [65]:
df['NA_Sales']=pd.to_numeric(df['NA_Sales']
               .astype('string')
               .str.strip()
               .str.replace(r'[^\d.]','', regex=True),
                errors='coerce')
df['NA_Sales'].head(10)

0     41.49
1     29.08
2     15.85
3     15.75
4     11.27
5      23.2
6     11.38
7     14.03
8     14.59
13    26.93
Name: NA_Sales, dtype: Float64

In [66]:
df.loc[ (df['NA_Sales']<0) | (df['NA_Sales']>100), 'NA_Sales']=np.nan

# Global_Sales

In [67]:
df['Global_Sales'].unique()

array([82.74, 40.24, 35.82, 33.  , 31.37, 30.26, 30.01, 29.02, 28.62,
       28.31, 24.76, 23.42, 23.1 , 22.72, 22.  , 21.82, 21.4 , 20.81,
       20.61, 20.22, 18.36, 18.14, 17.28, 16.38, 16.15, 15.85, 15.32,
       15.3 , 14.98, 14.76, 14.64, 14.35, 14.24, 14.03, 13.73, 13.51,
       13.46, 13.1 , 13.04, 12.73, 12.27, 12.21, 12.14, 11.98, 11.9 ,
       11.89, 11.66, 11.52, 11.33, 11.18, 11.02, 10.95, 10.79, 10.77,
       10.69, 10.57, 10.55, 10.49, 10.42, 10.26, 10.21,  9.88,  9.87,
        9.82,  9.76,  9.72,  9.59,  9.52,  9.49,  9.32,  9.3 ,  9.2 ,
        9.09,  9.02,  8.84,  8.76,  8.49,  8.42,  8.33,  8.24,  8.11,
        8.09,  8.06,  8.05,  7.86,  7.84,  7.81,  7.72,  7.69,  7.67,
        7.6 ,  7.58,  7.46,  7.45,  7.37,  7.34,  7.31,  7.3 ,  7.27,
        7.23,  7.2 ,  7.16,  7.13,  7.07,  6.96,  6.95,  6.91,  6.9 ,
        6.83,  6.82,  6.81,  6.76,  6.73,  6.72,  6.69,  6.67,  6.6 ,
        6.59,  6.56,  6.51,  6.5 ,  6.43,  6.41,  6.4 ,  6.39,  6.36,
        6.34,  6.31,  6.3 ,  6.28,  6.27,  6.24,  6.11,  6.05,  6.03,
        5.99,  5.95,  5.92,  5.84,  5.83,  5.82,  5.74,  5.72,  5.65,
        5.58,  5.57,  5.55,  5.53,  5.51,  5.5 ,  5.49,  5.47,  5.46,
        5.45,  5.43,  5.42,  5.36,  5.34,  5.31,  5.3 ,  5.29,  5.27,
        5.26,  5.24,  5.23,  5.21,  5.2 ,  5.19,  5.18,  5.17,  5.15,
        5.14,  5.13,  5.12,  5.11,  5.08,  5.07,  5.05,  5.02,  5.01,
        5.  ,  4.98,  4.96,  4.94,  4.91,  4.9 ,  4.88,  4.87,  4.85,
        4.84,  4.83,  4.82,  4.79,  4.77,  4.76,  4.73,  4.7 ,  4.68,
        4.67,  4.64,  4.63,  4.62,  4.61,  4.6 ,  4.58,  4.57,  4.55,
        4.53,  4.5 ,  4.49,  4.48,  4.47,  4.45,  4.44,  4.42,  4.41,
        4.39,  4.38,  4.37,  4.35,  4.34,  4.33,  4.31,  4.26,  4.25,
        4.24,  4.23,  4.22,  4.21,  4.2 ,  4.19,  4.17,  4.16,  4.14,
        4.12,  4.11,  4.1 ,  4.09,  4.08,  4.07,  4.06,  4.05,  4.03,
        4.02,  4.01,  4.  ,  3.99,  3.98,  3.92,  3.91,  3.9 ,  3.89,
        3.88,  3.87,  3.85,  3.84,  3.83,  3.82,  3.81,  3.79,  3.78,
        3.77,  3.76,  3.73,  3.72,  3.71,  3.7 ,  3.69,  3.67,  3.66,
        3.65,  3.64,  3.63,  3.62,  3.61,  3.6 ,  3.59,  3.58,  3.56,
        3.54,  3.53,  3.52,  3.51,  3.5 ,  3.49,  3.48,  3.46,  3.45,
        3.44,  3.43,  3.42,  3.41,  3.4 ,  3.39,  3.38,  3.36,  3.34,
        3.33,  3.32,  3.31,  3.28,  3.27,  3.26,  3.24,  3.23,  3.22,
        3.21,  3.2 ,  3.19,  3.18,  3.17,  3.16,  3.15,  3.14,  3.13,
        3.12,  3.11,  3.09,  3.08,  3.07,  3.05,  3.04,  3.03,  3.02,
        3.  ,  2.99,  2.98,  2.97,  2.96,  2.95,  2.94,  2.93,  2.92,
        2.91,  2.9 ,  2.89,  2.88,  2.87,  2.86,  2.85,  2.84,  2.83,
        2.82,  2.81,  2.8 ,  2.79,  2.78,  2.77,  2.76,  2.75,  2.74,
        2.73,  2.72,  2.71,  2.7 ,  2.69,  2.68,  2.67,  2.66,  2.65,
        2.64,  2.63,  2.62,  2.61,  2.6 ,  2.59,  2.58,  2.57,  2.56,
        2.54,  2.53,  2.52,  2.51,  2.5 ,  2.49,  2.48,  2.47,  2.46,
        2.45,  2.44,  2.43,  2.42,  2.41,  2.4 ,  2.39,  2.38,  2.37,
        2.36,  2.35,  2.34,  2.33,  2.32,  2.31,  2.3 ,  2.29,  2.28,
        2.27,  2.26,  2.25,  2.24,  2.23,  2.22,  2.21,  2.2 ,  2.19,
        2.18,  2.17,  2.16,  2.15,  2.14,  2.13,  2.12,  2.11,  2.1 ,
        2.09,  2.08,  2.07,  2.06,  2.05,  2.04,  2.03,  2.02,  2.01,
        2.  ,  1.99,  1.98,  1.97,  1.96,  1.95,  1.94,  1.93,  1.92,
        1.91,  1.9 ,  1.89,  1.88,  1.87,  1.86,  1.85,  1.84,  1.83,
        1.82,  1.81,  1.8 ,  1.79,  1.78,  1.77,  1.76,  1.75,  1.74,
        1.73,  1.72,  1.71,  1.7 ,  1.69,  1.68,  1.67,  1.66,  1.65,
        1.64,  1.63,  1.62,  1.61,  1.6 ,  1.59,  1.58,  1.57,  1.56,
        1.55,  1.54,  1.53,  1.52,  1.51,  1.5 ,  1.49,  1.48,  1.47,
        1.46,  1.45,  1.44,  1.43,  1.42,  1.41,  1.4 ,  1.39,  1.38,
        1.37,  1.36,  1.35,  1.34,  1.33,  1.32,  1.31,  1.3 ,  1.29,
        1.28,  1.27,  1.26,  1.25,  1.24,  1.23,  1.22,  1.21,  1.2 ,
        1.19,  1.18,  1.17,  1.16,  1.15,  1.14,  1.13,  1.12,  1.11,
        1.1 ,  1.09,  1.08,  1.07,  1.06,  1.05,  1.04,  1.03,  1.02,
        1.01,  1.  ,  0.99,  0.98,  0.97,  0.96,  0.95,  0.94,  0.93,
        0.92,  0.91,  0.9 ,  0.89,  0.88,  0.87,  0.86,  0.85,  0.84,
        0.83,  0.82,  0.81,  0.8 ,  0.79,  0.78,  0.77,  0.76,  0.75,
        0.74,  0.73,  0.72,  0.71,  0.7 ,  0.69,  0.68,  0.67,  0.66,
        0.65,  0.64,  0.63,  0.62,  0.61,  0.6 ,  0.59,  0.58,  0.57,
        0.56,  0.55,  0.54,  0.53,  0.52,  0.51,  0.5 ,  0.49,  0.48,
        0.47,  0.46,  0.45,  0.44,  0.43,  0.42,  0.41,  0.4 ,  0.39,
        0.38,  0.37,  0.36,  0.35,  0.34,  0.33,  0.32,  0.31,  0.3 ])

In [68]:
df['Global_Sales']=pd.to_numeric(df['Global_Sales']
            .replace(r'[^\d.]','', regex=True),
            errors='coerce')

df['Global_Sales'].head(10)

0     82.74
1     40.24
2     35.82
3     33.00
4     31.37
5     30.26
6     30.01
7     29.02
8     28.62
13    28.31
Name: Global_Sales, dtype: float64

In [69]:
df.loc[ (df['Global_Sales']<0) | (df['Global_Sales']>100), 'Global_Sales']=np.nan

# NA_Profit

In [70]:
df['NA_Profit'].unique()

array([1.2447e+01, 8.7240e+00, 4.7550e+00, 4.7250e+00, 3.3810e+00,
       6.9600e+00, 3.4140e+00, 4.2090e+00, 4.3770e+00, 8.0790e+00,
       2.7210e+00, 2.9430e+00, 2.7000e+00, 2.6820e+00, 2.7270e+00,
       4.4910e+00, 2.1030e+00, 2.8290e+00, 3.8340e+00, 1.4250e+00,
       1.9260e+00, 3.2490e+00, 2.8620e+00, 2.8890e+00, 2.5230e+00,
       1.8180e+00, 1.6710e+00, 1.0320e+00, 2.0550e+00, 2.7090e+00,
       1.7670e+00, 2.9010e+00, 1.5510e+00, 1.7310e+00, 1.4970e+00,
       2.4750e+00, 2.5560e+00, 1.6620e+00, 2.0970e+00, 2.0250e+00,
       1.7940e+00, 7.6500e-01, 1.4220e+00, 2.3910e+00, 1.1400e+00,
       1.3200e+00, 2.0730e+00, 9.0300e-01, 1.8480e+00, 1.2690e+00,
       2.0280e+00, 1.2060e+00, 1.4670e+00, 8.8800e-01, 1.4280e+00,
       1.7970e+00, 1.3020e+00, 1.5240e+00, 1.8150e+00, 2.0160e+00,
       2.1090e+00, 1.6650e+00, 1.0980e+00, 1.9890e+00, 1.2270e+00,
       1.7520e+00, 1.1640e+00, 1.7730e+00, 1.3080e+00, 1.6740e+00,
       6.0300e-01, 1.3380e+00, 1.5090e+00, 1.0620e+00, 3.3300e-01,
       5.3700e-01, 2.0460e+00, 1.1430e+00, 8.7300e-01, 3.1800e-01,
       2.9400e-01, 1.7400e+00, 7.7400e-01, 6.8400e-01, 8.4600e-01,
       2.1840e+00, 8.7000e-01, 8.7900e-01, 8.4000e-01, 1.2300e+00,
       1.1340e+00, 1.6170e+00, 9.7200e-01, 1.4370e+00, 1.1490e+00,
       1.3560e+00, 1.0530e+00, 8.5500e-01, 9.8100e-01, 1.1040e+00,
       1.3230e+00, 9.3900e-01, 7.4100e-01, 1.2360e+00, 1.2420e+00,
       2.3400e-01, 8.1300e-01, 8.3100e-01, 9.6900e-01, 1.0500e+00,
       1.2450e+00, 9.3000e-01, 2.5200e-01, 5.0100e-01, 8.3700e-01,
       2.3700e-01, 9.7500e-01, 1.1220e+00, 7.9200e-01, 1.4940e+00,
       7.7100e-01, 1.0920e+00, 1.1100e+00, 1.2030e+00, 2.1000e-02,
       9.3300e-01, 1.1760e+00, 1.2150e+00, 7.3500e-01, 1.3410e+00,
       7.8900e-01, 9.5400e-01, 7.2300e-01, 5.6400e-01, 1.9800e-01,
       6.7800e-01, 7.4700e-01, 8.9100e-01, 7.6200e-01, 8.8500e-01,
       9.8400e-01, 8.1000e-01, 8.9700e-01, 1.4100e-01, 9.4200e-01,
       7.8600e-01, 9.6300e-01, 8.1600e-01, 6.2100e-01, 5.9100e-01,
       5.2200e-01, 6.5400e-01, 9.0600e-01, 4.8600e-01, 5.7600e-01,
       9.9900e-01, 3.6600e-01, 6.9000e-01, 1.2780e+00, 1.9500e-01,
       7.2900e-01, 6.9600e-01, 3.2400e-01, 5.7000e-01, 6.3000e-01,
       2.8800e-01, 4.9200e-01, 5.9400e-01, 1.0770e+00, 9.6600e-01,
       5.8800e-01, 7.9800e-01, 5.1000e-01, 1.8000e-01, 1.0200e+00,
       6.1500e-01, 1.0260e+00, 7.7700e-01, 1.0080e+00, 9.1800e-01,
       1.0470e+00, 1.0170e+00, 5.5500e-01, 6.9300e-01, 1.1940e+00,
       8.6700e-01, 0.0000e+00, 8.2200e-01, 7.6800e-01, 5.7300e-01,
       1.7100e-01, 8.4000e-02, 7.0800e-01, 5.1900e-01, 9.1500e-01,
       5.6100e-01, 5.8200e-01, 6.2400e-01, 6.8700e-01, 7.2600e-01,
       7.8000e-01, 5.6700e-01, 5.3400e-01, 4.6500e-01, 9.5700e-01,
       1.2540e+00, 1.2630e+00, 1.0890e+00, 6.0000e-02, 4.6200e-01,
       8.0100e-01, 3.0000e-02, 6.5700e-01, 6.0900e-01, 9.0900e-01,
       6.6000e-01, 2.7600e-01, 8.2500e-01, 1.2000e+00, 7.5300e-01,
       6.3300e-01, 6.6900e-01, 4.2300e-01, 9.0000e-01, 4.3800e-01,
       2.6400e-01, 3.9000e-01, 3.8400e-01, 6.7500e-01, 6.0600e-01,
       1.0140e+00, 6.1200e-01, 1.1370e+00, 4.2000e-01, 1.2090e+00,
       4.9500e-01, 2.1300e-01, 6.4200e-01, 4.2600e-01, 6.3900e-01,
       7.9500e-01, 7.0500e-01, 3.6000e-02, 5.0400e-01, 3.3600e-01,
       8.3400e-01, 4.1400e-01, 6.4500e-01, 3.5400e-01, 3.9900e-01,
       2.0100e-01, 4.5900e-01, 3.4500e-01, 2.7900e-01, 6.3600e-01,
       7.4400e-01, 4.8000e-02, 2.6100e-01, 6.6300e-01, 4.3200e-01,
       4.4700e-01, 3.4200e-01, 7.2000e-01, 5.4600e-01, 4.1100e-01,
       5.7900e-01, 1.7400e-01, 4.7700e-01, 7.5900e-01, 6.9900e-01,
       1.5000e-02, 4.8300e-01, 7.1400e-01, 4.7100e-01, 4.6800e-01,
       3.6900e-01, 4.9800e-01, 3.5100e-01, 8.5200e-01, 1.7700e-01,
       6.2700e-01, 7.1700e-01, 4.0200e-01, 3.3900e-01, 2.5800e-01,
       5.2500e-01, 1.3800e-01, 4.2900e-01, 4.8900e-01, 4.3500e-01,
       4.4100e-01, 5.9700e-01, 4.5000e-01, 2.4000e-01, 4.0800e-01,
       1.5000e-01, 7.5000e-02, 2.8500e-01, 3.8100e-01, 9.0000e-03,
       5.1600e-01, 2.1900e-01, 5.2800e-01, 4.0500e-01, 4.4400e-01,
       4.5600e-01, 5.5800e-01, 6.1800e-01, 2.0400e-01, 2.7300e-01,
       5.0700e-01, 2.4000e-02, 3.8700e-01, 6.5100e-01, 7.5000e-01,
       3.0300e-01, 4.7400e-01, 3.1200e-01, 6.6600e-01, 5.4900e-01,
       1.8300e-01, 5.5200e-01, 2.9700e-01, 4.5300e-01, 2.7000e-02,
       1.2000e-01, 7.5600e-01, 3.9600e-01, 6.0000e-03, 3.1500e-01,
       8.7000e-02, 3.5700e-01, 2.6700e-01, 9.0000e-02, 3.6000e-01,
       3.7200e-01, 3.7500e-01, 3.2100e-01, 3.0600e-01, 2.0700e-01,
       5.8500e-01, 6.0000e-01, 2.2800e-01, 1.8900e-01, 2.7000e-01,
       1.4400e-01, 1.9200e-01, 1.1100e-01, 3.9300e-01, 4.5000e-02,
       3.6300e-01, 1.4700e-01, 3.9000e-02, 5.4300e-01, 3.7800e-01,
       2.4300e-01, 2.3100e-01, 3.0000e-01, 3.4800e-01, 4.1700e-01,
       2.5500e-01, 1.5600e-01, 1.5300e-01, 1.1400e-01, 1.8600e-01,
       3.2700e-01, 5.1300e-01, 3.0900e-01, 1.0200e-01, 4.8000e-01,
       1.6200e-01, 4.2000e-02, 3.0000e-03, 2.4600e-01, 2.4900e-01,
       3.3000e-02, 2.8200e-01, 5.3100e-01, 2.1000e-01, 2.9100e-01,
       2.2500e-01, 1.0500e-01, 2.1600e-01, 2.2200e-01, 5.4000e-02,
       3.3000e-01, 1.6800e-01, 7.8000e-02, 6.3000e-02, 6.6000e-02,
       1.5900e-01, 1.6500e-01, 6.9000e-02, 1.1700e-01, 9.6000e-02,
       1.3500e-01, 1.2300e-01, 9.3000e-02, 7.2000e-02, 1.8000e-02,
       1.2900e-01, 1.3200e-01, 5.7000e-02, 1.2000e-02, 5.1000e-02,
       1.0800e-01, 9.9000e-02, 8.1000e-02, 1.2600e-01])

In [71]:
df['NA_Profit']=(pd.to_numeric(df['NA_Profit']
    .replace(r'[\d.]', '', regex=True),
    errors='coerce').round(2)
)
df['NA_Profit'].sample(10)

683     0.00
1257    0.07
354     0.18
711     0.11
2335    0.13
3574    0.07
2413    0.14
375     0.64
4130    0.07
1757    0.29
Name: NA_Profit, dtype: float64

In [72]:
df.loc[ (df['NA_Profit']<0) | (df['NA_Profit']>100), 'NA_Profit']=np.nan

# Global_Profit

In [73]:
df['Global_Profit'].unique()

array([24.822, 12.072, 10.746,  9.9  ,  9.411,  9.078,  9.003,  8.706,
        8.586,  8.493,  7.428,  7.026,  6.93 ,  6.816,  6.6  ,  6.546,
        6.42 ,  6.243,  6.183,  6.066,  5.508,  5.442,  5.184,  4.914,
        4.845,  4.755,  4.596,  4.59 ,  4.494,  4.428,  4.392,  4.305,
        4.272,  4.209,  4.119,  4.053,  4.038,  3.93 ,  3.912,  3.819,
        3.681,  3.663,  3.642,  3.594,  3.57 ,  3.567,  3.498,  3.456,
        3.399,  3.354,  3.306,  3.285,  3.237,  3.231,  3.207,  3.171,
        3.165,  3.147,  3.126,  3.078,  3.063,  2.964,  2.961,  2.946,
        2.928,  2.916,  2.877,  2.856,  2.847,  2.796,  2.79 ,  2.76 ,
        2.727,  2.706,  2.652,  2.628,  2.547,  2.526,  2.499,  2.472,
        2.433,  2.427,  2.418,  2.415,  2.358,  2.352,  2.343,  2.316,
        2.307,  2.301,  2.28 ,  2.274,  2.238,  2.235,  2.211,  2.202,
        2.193,  2.19 ,  2.181,  2.169,  2.16 ,  2.148,  2.139,  2.121,
        2.088,  2.085,  2.073,  2.07 ,  2.049,  2.046,  2.043,  2.028,
        2.019,  2.016,  2.007,  2.001,  1.98 ,  1.977,  1.968,  1.953,
        1.95 ,  1.929,  1.923,  1.92 ,  1.917,  1.908,  1.902,  1.893,
        1.89 ,  1.884,  1.881,  1.872,  1.833,  1.815,  1.809,  1.797,
        1.785,  1.776,  1.752,  1.749,  1.746,  1.722,  1.716,  1.695,
        1.674,  1.671,  1.665,  1.659,  1.653,  1.65 ,  1.647,  1.641,
        1.638,  1.635,  1.629,  1.626,  1.608,  1.602,  1.593,  1.59 ,
        1.587,  1.581,  1.578,  1.572,  1.569,  1.563,  1.56 ,  1.557,
        1.554,  1.551,  1.545,  1.542,  1.539,  1.536,  1.533,  1.524,
        1.521,  1.515,  1.506,  1.503,  1.5  ,  1.494,  1.488,  1.482,
        1.473,  1.47 ,  1.464,  1.461,  1.455,  1.452,  1.449,  1.446,
        1.437,  1.431,  1.428,  1.419,  1.41 ,  1.404,  1.401,  1.392,
        1.389,  1.386,  1.383,  1.38 ,  1.374,  1.371,  1.365,  1.359,
        1.35 ,  1.347,  1.344,  1.341,  1.335,  1.332,  1.326,  1.323,
        1.317,  1.314,  1.311,  1.305,  1.302,  1.299,  1.293,  1.278,
        1.275,  1.272,  1.269,  1.266,  1.263,  1.26 ,  1.257,  1.251,
        1.248,  1.242,  1.236,  1.233,  1.23 ,  1.227,  1.224,  1.221,
        1.218,  1.215,  1.209,  1.206,  1.203,  1.2  ,  1.197,  1.194,
        1.176,  1.173,  1.17 ,  1.167,  1.164,  1.161,  1.155,  1.152,
        1.149,  1.146,  1.143,  1.137,  1.134,  1.131,  1.128,  1.119,
        1.116,  1.113,  1.11 ,  1.107,  1.101,  1.098,  1.095,  1.092,
        1.089,  1.086,  1.083,  1.08 ,  1.077,  1.074,  1.068,  1.062,
        1.059,  1.056,  1.053,  1.05 ,  1.047,  1.044,  1.038,  1.035,
        1.032,  1.029,  1.026,  1.023,  1.02 ,  1.017,  1.014,  1.008,
        1.002,  0.999,  0.996,  0.993,  0.984,  0.981,  0.978,  0.972,
        0.969,  0.966,  0.963,  0.96 ,  0.957,  0.954,  0.951,  0.948,
        0.945,  0.942,  0.939,  0.936,  0.933,  0.927,  0.924,  0.921,
        0.915,  0.912,  0.909,  0.906,  0.9  ,  0.897,  0.894,  0.891,
        0.888,  0.885,  0.882,  0.879,  0.876,  0.873,  0.87 ,  0.867,
        0.864,  0.861,  0.858,  0.855,  0.852,  0.849,  0.846,  0.843,
        0.84 ,  0.837,  0.834,  0.831,  0.828,  0.825,  0.822,  0.819,
        0.816,  0.813,  0.81 ,  0.807,  0.804,  0.801,  0.798,  0.795,
        0.792,  0.789,  0.786,  0.783,  0.78 ,  0.777,  0.774,  0.771,
        0.768,  0.762,  0.759,  0.756,  0.753,  0.75 ,  0.747,  0.744,
        0.741,  0.738,  0.735,  0.732,  0.729,  0.726,  0.723,  0.72 ,
        0.717,  0.714,  0.711,  0.708,  0.705,  0.702,  0.699,  0.696,
        0.693,  0.69 ,  0.687,  0.684,  0.681,  0.678,  0.675,  0.672,
        0.669,  0.666,  0.663,  0.66 ,  0.657,  0.654,  0.651,  0.648,
        0.645,  0.642,  0.639,  0.636,  0.633,  0.63 ,  0.627,  0.624,
        0.621,  0.618,  0.615,  0.612,  0.609,  0.606,  0.603,  0.6  ,
        0.597,  0.594,  0.591,  0.588,  0.585,  0.582,  0.579,  0.576,
        0.573,  0.57 ,  0.567,  0.564,  0.561,  0.558,  0.555,  0.552,
        0.549,  0.546,  0.543,  0.54 ,  0.537,  0.534,  0.531,  0.528,
        0.525,  0.522,  0.519,  0.516,  0.513,  0.51 ,  0.507,  0.504,
        0.501,  0.498,  0.495,  0.492,  0.489,  0.486,  0.483,  0.48 ,
        0.477,  0.474,  0.471,  0.468,  0.465,  0.462,  0.459,  0.456,
        0.453,  0.45 ,  0.447,  0.444,  0.441,  0.438,  0.435,  0.432,
        0.429,  0.426,  0.423,  0.42 ,  0.417,  0.414,  0.411,  0.408,
        0.405,  0.402,  0.399,  0.396,  0.393,  0.39 ,  0.387,  0.384,
        0.381,  0.378,  0.375,  0.372,  0.369,  0.366,  0.363,  0.36 ,
        0.357,  0.354,  0.351,  0.348,  0.345,  0.342,  0.339,  0.336,
        0.333,  0.33 ,  0.327,  0.324,  0.321,  0.318,  0.315,  0.312,
        0.309,  0.306,  0.303,  0.3  ,  0.297,  0.294,  0.291,  0.288,
        0.285,  0.282,  0.279,  0.276,  0.273,  0.27 ,  0.267,  0.264,
        0.261,  0.258,  0.255,  0.252,  0.249,  0.246,  0.243,  0.24 ,
        0.237,  0.234,  0.231,  0.228,  0.225,  0.222,  0.219,  0.216,
        0.213,  0.21 ,  0.207,  0.204,  0.201,  0.198,  0.195,  0.192,
        0.189,  0.186,  0.183,  0.18 ,  0.177,  0.174,  0.171,  0.168,
        0.165,  0.162,  0.159,  0.156,  0.153,  0.15 ,  0.147,  0.144,
        0.141,  0.138,  0.135,  0.132,  0.129,  0.126,  0.123,  0.12 ,
        0.117,  0.114,  0.111,  0.108,  0.105,  0.102,  0.099,  0.096,
        0.093,  0.09 ])

In [74]:
df['Global_Profit']=(pd.to_numeric(df['Global_Profit']
    .replace(r'[^\d.]', '', regex=True),
    errors='coerce').round(2)
)
df['Global_Profit'].head(10)

0     24.82
1     12.07
2     10.75
3      9.90
4      9.41
5      9.08
6      9.00
7      8.71
8      8.59
13     8.49
Name: Global_Profit, dtype: float64

In [75]:
df.loc[ (df['Global_Profit']<0) | (df['Global_Profit']>100), 'Global_Profit']=np.nan

# Check

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5893 entries, 0 to 5908
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           5893 non-null   int64
 1   Name           5893 non-null   string
 2   Platform       5893 non-null   category
 3   Year           5893 non-null   int64
 4   Month          5893 non-null   category
 5   Genre          5893 non-null   category
 6   Publisher      5851 non-null   category
 7   Country        5893 non-null   category
 8   City           5893 non-null   category
 9   State          5893 non-null   category
 10  Region         5866 non-null   category
 11  NA_Sales       5893 non-null   Float64
 12  Global_Sales   5893 non-null   float64
 13  NA_Profit      5893 non-null   float64
 14  Global_Profit  5893 non-null   float64
dtypes: Float64(1), category(8), float64(3), int64(2), string(1)
memory usage: 457.4 KB

In [77]:
df.isna().sum()

Rank              0
Name              0
Platform          0
Year              0
Month             0
Genre             0
Publisher        42
Country           0
City              0
State             0
Region           27
NA_Sales          0
Global_Sales      0
NA_Profit         0
Global_Profit     0
dtype: int64

In [78]:
pd.set_option('display.max_rows',None)
df[df.isna().any(axis=1)]

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
13,10,Duck Hunt,NES,2010,Oct,Shooter,Nintendo,USA,Dallas,Texas,<NA>,26.93,28.31,8.08,8.49
38,35,Call Of Duty Black Ops Ii,PS3,2010,Nov,Shooter,Activision,USA,Stockton,California,<NA>,4.99,14.03,1.50,4.21
53,50,Pokemon Omega Rubypokemon Alpha Sapphire,3DS,2010,Feb,Role Playing,Nintendo,USA,New York City,New York,<NA>,4.23,11.33,1.27,3.40
84,78,Fifa 16,PS4,2010,Jun,Sports,Electronic Arts,USA,Carrollton,Texas,<NA>,1.11,8.49,0.33,2.55
126,120,Uncharted 2 Among Thieves,PS3,2010,Dec,Action,Sony Computer Entertainment,USA,Los Angeles,California,<NA>,3.27,6.73,0.98,2.02
210,204,Super Smash Bros For Wii U And 3Ds,WIIU,2010,Dec,Fighting,Nintendo,USA,New York City,New York,<NA>,2.59,5.02,0.78,1.51
225,219,Assassins Creed,PS3,2010,Mar,Adventure,Ubisoft,USA,Palm Coast,Florida,<NA>,1.91,4.83,0.57,1.45
243,237,The Last Of Us,PS4,2010,Sep,Action,Sony Computer Entertainment,USA,Lakeville,Minnesota,<NA>,1.78,4.55,0.53,1.36
480,471,Wwe Smackdown Vs Raw 2006,PS2,2010,Mar,Fighting,<NA>,USA,New York City,New York,East,1.57,3.00,0.47,0.90
950,942,Gran Turismo Concept 2001 Tokyo,PS2,2011,May,Racing,<NA>,USA,Smyrna,Georgia,South,0.0,1.84,0.00,0.55
1313,1305,Triple Play 99,PS,2013,Aug,Sports,<NA>,USA,Appleton,Wisconsin,Central,0.81,1.46,0.24,0.44
1662,1651,Nascar Thunder 2003,PS2,2015,Jun,Racing,<NA>,USA,Woodland,California,West,0.6,1.22,0.18,0.37
1675,1664,Shrek Shrek 2 2In1 Gameboy Advance Video,GBA,2011,Jul,Misc,<NA>,USA,San Diego,California,West,0.87,1.21,0.26,0.36
2127,2116,Suikoden Iii,PS2,2012,Mar,Role Playing,<NA>,USA,Pasadena,Texas,Central,0.29,0.98,0.09,0.29
2186,2175,Wheel Of Fortune,PS2,2012,Feb,Misc,<NA>,USA,Newark,Delaware,East,0.47,0.95,0.14,0.28
2235,2224,Bentleys Hackpack,GBA,2012,Mar,Misc,<NA>,USA,New York City,New York,East,0.67,0.93,0.20,0.28
2249,2238,Teenage Mutant Ninja Turtles,GBA,2012,May,Action,<NA>,USA,Philadelphia,Pennsylvania,East,0.67,0.93,0.20,0.28
2299,2288,Namco Museum,XB,2012,Jul,Misc,<NA>,USA,Toledo,Ohio,East,0.77,0.91,0.23,0.27
2308,2297,Rhythm Heaven,WII,2012,Apr,Misc,<NA>,USA,Albuquerque,New Mexico,West,0.13,0.90,0.04,0.27
2341,2330,Blitz The League,PS2,2012,Jan,Sports,<NA>,USA,Seattle,Washington,West,0.74,0.89,0.22,0.27
2453,2442,Harry Potter And The Order Of The Phoenix,DS,2013,May,Action,Electronic Arts,USA,Philadelphia,Pennsylvania,<NA>,0.28,0.85,0.08,0.26
2454,2443,Rampage World Tour,PS,2013,Jun,Action,Gt Interactive,USA,Waco,Texas,<NA>,0.47,0.85,0.14,0.26
2455,2444,Burnout Legends,PSP,2013,Jul,Racing,Electronic Arts,USA,Thousand Oaks,California,<NA>,0.7,0.85,0.21,0.26
2456,2445,Wwe 2K15,PS3,2013,Aug,Sports,Take Two Interactive,USA,Freeport,Illinois,<NA>,0.36,0.85,0.11,0.26
2497,2486,Madden Nfl 07,PSP,2013,Jan,Sports,<NA>,USA,Lakewood,New Jersey,East,0.77,0.83,0.23,0.25
2504,2493,The Game Of Life,PS,2013,Aug,Misc,<NA>,USA,Santa Ana,California,West,0.46,0.83,0.14,0.25
2510,2499,Mlb Slugfest 2003,PS2,2013,Feb,Sports,<NA>,USA,Los Angeles,California,West,0.41,0.83,0.12,0.25
2557,2546,Final Fantasy Type0,PSP,2013,Jan,Role Playing,<NA>,USA,Seattle,Washington,West,0.0,0.81,0.00,0.24
2604,2593,Tales Of Destiny 2,PS2,2013,Dec,Role Playing,Namco Bandai Games,USA,Harlingen,Texas,<NA>,0.0,0.80,0.00,0.24
2605,2594,Capcoms Soccer Shootout,SNES,2013,Jan,Sports,Nintendo,USA,Louisville,Kentucky,<NA>,0.0,0.80,0.00,0.24
2606,2595,Sniper Ghost Warrior,PS3,2013,Feb,Shooter,City Interactive,USA,Louisville,Kentucky,<NA>,0.26,0.80,0.08,0.24
2607,2596,The Godfather Ii,X360,2013,Mar,Action,Electronic Arts,USA,Louisville,Kentucky,<NA>,0.47,0.79,0.14,0.24
2789,2778,Madden Nfl 11,WII,2015,May,Sports,<NA>,USA,Lawrence,Indiana,Central,0.7,0.74,0.21,0.22
2799,2788,Warioware Twisted,GBA,2010,Mar,Puzzle,<NA>,Australia,Melbourne,Victoria,Other,0.16,0.74,0.05,0.22
2842,2831,God Eater,PSP,2010,Oct,Action,<NA>,Australia,Sydney,New South Wales,West,0.0,0.72,0.00,0.22
3043,3032,Rift,PC,2011,Jul,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.44,0.67,0.13,0.20
3172,3161,Nicktoons Collection Game Boy Advance Video Vo...,GBA,2012,Apr,Misc,<NA>,Australia,Sydney,New South Wales,West,0.46,0.64,0.14,0.19
3179,3168,Spongebob Squarepants Game Boy Advance Video V...,GBA,2012,Nov,Misc,<NA>,Australia,Sydney,New South Wales,West,0.46,0.64,0.14,0.19
3481,3470,Nascar Dirt To Daytona,PS2,2012,Jan,Racing,<NA>,Australia,Sydney,New South Wales,West,0.28,0.58,0.08,0.17
3514,3503,Madden Nfl 2002,XB,2013,Oct,Sports,<NA>,Australia,Sydney,New South Wales,West,0.53,0.58,0.16,0.17
3715,3704,Two Worlds Ii,X360,2014,Jul,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.4,0.54,0.12,0.16
3779,3768,Spongebob Squarepants Game Boy Advance Video V...,GBA,2014,Nov,Misc,<NA>,Australia,Sydney,New South Wales,West,0.38,0.53,0.11,0.16
3979,3968,Chopper Command,2600,2014,Jul,Shooter,Activision,Australia,Sydney,New South Wales,<NA>,0.47,0.50,0.14,0.15
3980,3969,Activision Anthology,PS2,2014,Aug,Misc,Activision,Australia,Sydney,New South Wales,<NA>,0.25,0.50,0.08,0.15
3981,3970,Crash Mind Over Mutant,PS2,2014,Sep,Platform,Vivendi Games,Australia,Sydney,New South Wales,<NA>,0.25,0.50,0.08,0.15
3982,3971,Wwe 2K16,X360,2014,Oct,Sports,Take Two Interactive,Australia,Sydney,New South Wales,<NA>,0.27,0.50,0.08,0.15
3983,3972,Lego The Hobbit,X360,2014,Nov,Action,Warner Bros Interactive Entertainment,Australia,Sydney,New South Wales,<NA>,0.2,0.50,0.06,0.15
3984,3973,Babysitting Mama,WII,2014,Dec,Simulation,505 Games,Australia,Sydney,New South Wales,<NA>,0.34,0.50,0.10,0.15
3985,3974,Boogie,WII,2014,Jan,Misc,Electronic Arts,Australia,Sydney,New South Wales,<NA>,0.43,0.50,0.13,0.15
3986,3975,Theatrhythm Final Fantasy,3DS,2014,Feb,Misc,Square Enix,Australia,Sydney,New South Wales,<NA>,0.22,0.50,0.07,0.15
3987,3976,Bleach Soul Resurreccion,PS3,2014,Mar,Fighting,Nippon Ichi Software,Australia,Sydney,New South Wales,<NA>,0.27,0.50,0.08,0.15
3988,3977,Madden Nfl 07,WII,2014,Apr,Sports,Electronic Arts,Australia,Sydney,New South Wales,<NA>,0.46,0.50,0.14,0.15
3989,3978,Rugrats In Paris The Movie,N64,2014,May,Action,Thq,Australia,Sydney,New South Wales,<NA>,0.4,0.50,0.12,0.15
4134,4123,Two Worlds Ii,PS3,2014,Jun,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.26,0.48,0.08,0.14
4158,4147,Sonic The Hedgehog,PS3,2015,Jun,Platform,<NA>,Australia,Sydney,New South Wales,West,0.0,0.48,0.00,0.14
4539,4528,The Fairly Odd Parents Game Boy Advance Video ...,GBA,2015,Mar,Misc,<NA>,Australia,Sydney,New South Wales,West,0.31,0.43,0.09,0.13
4549,4538,Nhl Slapshot,WII,2015,Jan,Sports,<NA>,Australia,Sydney,New South Wales,West,0.4,0.43,0.12,0.13
4648,4637,The Fairly Odd Parents Game Boy Advance Video ...,GBA,2015,Apr,Misc,<NA>,Australia,Sydney,New South Wales,West,0.3,0.42,0.09,0.13
4696,4685,Tera,PC,2015,Apr,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.24,0.41,0.07,0.12
4810,4799,Nfl Gameday 2003,PS2,2016,Oct,Sports,<NA>,Australia,Sydney,New South Wales,West,0.2,0.40,0.06,0.12
4878,4867,Harvest Moon Save The Homeland,PS2,2016,Jun,Simulation,<NA>,Australia,Sydney,New South Wales,West,0.19,0.40,0.06,0.12
5184,5173,Bejeweled 3,DS,2016,Dec,Puzzle,<NA>,Australia,Sydney,New South Wales,West,0.32,0.36,0.10,0.11
5208,5197,Cubix Robots For Everyone Clash N Bash,GBA,2016,Dec,Action,<NA>,Australia,Sydney,New South Wales,West,0.26,0.36,0.08,0.11
5315,5304,Dragon Ball Z Budokai Tenkaichi 2 Jp Sales,WII,2016,Nov,Action,<NA>,Australia,Sydney,New South Wales,West,0.15,0.35,0.04,0.10
5631,5620,Final Fantasy Xi,PS2,2017,Mar,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.08,0.32,0.02,0.10
5638,5627,Singularity,X360,2017,Oct,Shooter,<NA>,Australia,Sydney,New South Wales,West,0.24,0.32,0.07,0.10
5660,5649,Cartoon Network Collection Game Boy Advance Vi...,GBA,2017,Aug,Misc,<NA>,Australia,Sydney,New South Wales,West,0.23,0.32,0.07,0.10
5682,5671,Allstar Baseball 2005,PS2,2017,Jun,Sports,<NA>,Australia,Sydney,New South Wales,West,0.16,0.32,0.05,0.10
5874,5863,The Dukes Of Hazzard Ii Daisy Dukes It Out,PS,2017,Jun,Racing,<NA>,Australia,Sydney,New South Wales,West,0.17,0.30,0.05,0.09

In [79]:
pd.reset_option('display.max_rows')

In [80]:
df.dropna()  # After dropping null 69 values Total 5893 - 69=5824

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
0,1,Wii Sports,WII,2010,Jan,Sports,Nintendo,USA,Fairfield,California,West,41.49,82.74,12.45,24.82
1,2,Super Mario Bros,NES,2010,Feb,Platform,Nintendo,USA,Edmonds,Washington,West,29.08,40.24,8.72,12.07
2,3,Mario Kart Wii,WII,2010,Mar,Racing,Nintendo,USA,Louisville,Kentucky,South,15.85,35.82,4.76,10.75
3,4,Wii Sports Resort,WII,2010,Apr,Sports,Nintendo,USA,Round Rock,Texas,Central,15.75,33.00,4.72,9.90
4,5,Pokemon Redpokemon Blue,GB,2010,May,Role Playing,Nintendo,USA,Nashville,Tennessee,South,11.27,31.37,3.38,9.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5904,5890,Crazy Taxi Catch A Ride,GBA,2017,Sep,Racing,Thq,Australia,Sydney,New South Wales,West,0.21,0.30,0.06,0.09
5905,5891,Mysims Party,DS,2017,Oct,Simulation,Electronic Arts,Australia,Sydney,New South Wales,West,0.15,0.30,0.04,0.09
5906,5892,Harry Potter And The Order Of The Phoenix,X360,2017,Nov,Action,Electronic Arts,Australia,Sydney,New South Wales,West,0.24,0.30,0.07,0.09
5907,5893,Skylanders Superchargers,PS4,2017,Dec,Action,Activision,Australia,Sydney,New South Wales,West,0.17,0.30,0.05,0.09
5908,5894,Macross Digital Mission Vfx,PS,2017,Jan,Simulation,Namco Bandai Games,Australia,Sydney,New South Wales,West,0.0,0.30,0.00,0.09

In [81]:
df.duplicated().sum()

np.int64(0)

In [82]:
col=df.columns.drop('Rank')
col

Index(['Name', 'Platform', 'Year', 'Month', 'Genre', 'Publisher', 'Country',
       'City', 'State', 'Region', 'NA_Sales', 'Global_Sales', 'NA_Profit',
       'Global_Profit'],
      dtype='object')

In [83]:
df.duplicated(subset=col).sum()

np.int64(0)

In [84]:
df.dtypes

Rank                      int64
Name             string[python]
Platform               category
Year                      int64
Month                  category
Genre                  category
Publisher              category
Country                category
City                   category
State                  category
Region                 category
NA_Sales                Float64
Global_Sales            float64
NA_Profit               float64
Global_Profit           float64
dtype: object

In [85]:
df.value_counts()

Rank  Name                                        Platform  Year  Month  Genre       Publisher              Country    City           State            Region  NA_Sales  Global_Sales  NA_Profit  Global_Profit
1     Wii Sports                                  WII       2010  Jan    Sports      Nintendo               USA        Fairfield      California       West    41.49     82.74         12.45      24.82            1
3934  Burnout Revenge                             X360      2014  Sep    Racing      Electronic Arts        Australia  Sydney         New South Wales  West    0.42      0.51          0.13       0.15             1
3932  The Bigs                                    PS2       2014  Jul    Sports      Take Two Interactive   Australia  Sydney         New South Wales  West    0.25      0.51          0.08       0.15             1
3931  World Championship Poker                    XB        2014  Jun    Misc        Crave Entertainment    Australia  Sydney         New South Wales  West    0.37      0.51          0.11       0.15             1
3930  Nba 2K11                                    WII       2014  May    Action      Take Two Interactive   Australia  Sydney         New South Wales  West    0.47      0.51          0.14       0.15             1
                                                                                                                                                                                                                  ..
1954  Lego Indiana Jones The Original Adventures  PS3       2012  Sep    Action      Activision             USA        New York City  New York         East    0.44      1.06          0.13       0.32             1
1953  Hulk                                        PS2       2012  Aug    Action      Universal Interactive  USA        Redmond        Oregon           West    0.52      1.06          0.16       0.32             1
1952  Worms Armageddon                            PS        2012  Jul    Strategy    Microprose             USA        Seattle        Washington       West    0.18      1.06          0.05       0.32             1
1951  Mercenaries 2 World In Flames               X360      2012  Jun    Shooter     Electronic Arts        USA        Charlotte      North Carolina   South   0.65      1.06          0.20       0.32             1
5894  Macross Digital Mission Vfx                 PS        2017  Jan    Simulation  Namco Bandai Games     Australia  Sydney         New South Wales  West    0.0       0.30          0.00       0.09             1
Name: count, Length: 5824, dtype: int64

In [86]:
df.shape

(5893, 15)

In [87]:
(df.isnull().sum()/len(df)*100).round(2)

Rank             0.00
Name             0.00
Platform         0.00
Year             0.00
Month            0.00
Genre            0.00
Publisher        0.71
Country          0.00
City             0.00
State            0.00
Region           0.46
NA_Sales         0.00
Global_Sales     0.00
NA_Profit        0.00
Global_Profit    0.00
dtype: float64

In [88]:
pd.set_option('display.max_rows',None)
df[df.isnull().any(axis=1)]

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
13,10,Duck Hunt,NES,2010,Oct,Shooter,Nintendo,USA,Dallas,Texas,<NA>,26.93,28.31,8.08,8.49
38,35,Call Of Duty Black Ops Ii,PS3,2010,Nov,Shooter,Activision,USA,Stockton,California,<NA>,4.99,14.03,1.50,4.21
53,50,Pokemon Omega Rubypokemon Alpha Sapphire,3DS,2010,Feb,Role Playing,Nintendo,USA,New York City,New York,<NA>,4.23,11.33,1.27,3.40
84,78,Fifa 16,PS4,2010,Jun,Sports,Electronic Arts,USA,Carrollton,Texas,<NA>,1.11,8.49,0.33,2.55
126,120,Uncharted 2 Among Thieves,PS3,2010,Dec,Action,Sony Computer Entertainment,USA,Los Angeles,California,<NA>,3.27,6.73,0.98,2.02
210,204,Super Smash Bros For Wii U And 3Ds,WIIU,2010,Dec,Fighting,Nintendo,USA,New York City,New York,<NA>,2.59,5.02,0.78,1.51
225,219,Assassins Creed,PS3,2010,Mar,Adventure,Ubisoft,USA,Palm Coast,Florida,<NA>,1.91,4.83,0.57,1.45
243,237,The Last Of Us,PS4,2010,Sep,Action,Sony Computer Entertainment,USA,Lakeville,Minnesota,<NA>,1.78,4.55,0.53,1.36
480,471,Wwe Smackdown Vs Raw 2006,PS2,2010,Mar,Fighting,<NA>,USA,New York City,New York,East,1.57,3.00,0.47,0.90
950,942,Gran Turismo Concept 2001 Tokyo,PS2,2011,May,Racing,<NA>,USA,Smyrna,Georgia,South,0.0,1.84,0.00,0.55
1313,1305,Triple Play 99,PS,2013,Aug,Sports,<NA>,USA,Appleton,Wisconsin,Central,0.81,1.46,0.24,0.44
1662,1651,Nascar Thunder 2003,PS2,2015,Jun,Racing,<NA>,USA,Woodland,California,West,0.6,1.22,0.18,0.37
1675,1664,Shrek Shrek 2 2In1 Gameboy Advance Video,GBA,2011,Jul,Misc,<NA>,USA,San Diego,California,West,0.87,1.21,0.26,0.36
2127,2116,Suikoden Iii,PS2,2012,Mar,Role Playing,<NA>,USA,Pasadena,Texas,Central,0.29,0.98,0.09,0.29
2186,2175,Wheel Of Fortune,PS2,2012,Feb,Misc,<NA>,USA,Newark,Delaware,East,0.47,0.95,0.14,0.28
2235,2224,Bentleys Hackpack,GBA,2012,Mar,Misc,<NA>,USA,New York City,New York,East,0.67,0.93,0.20,0.28
2249,2238,Teenage Mutant Ninja Turtles,GBA,2012,May,Action,<NA>,USA,Philadelphia,Pennsylvania,East,0.67,0.93,0.20,0.28
2299,2288,Namco Museum,XB,2012,Jul,Misc,<NA>,USA,Toledo,Ohio,East,0.77,0.91,0.23,0.27
2308,2297,Rhythm Heaven,WII,2012,Apr,Misc,<NA>,USA,Albuquerque,New Mexico,West,0.13,0.90,0.04,0.27
2341,2330,Blitz The League,PS2,2012,Jan,Sports,<NA>,USA,Seattle,Washington,West,0.74,0.89,0.22,0.27
2453,2442,Harry Potter And The Order Of The Phoenix,DS,2013,May,Action,Electronic Arts,USA,Philadelphia,Pennsylvania,<NA>,0.28,0.85,0.08,0.26
2454,2443,Rampage World Tour,PS,2013,Jun,Action,Gt Interactive,USA,Waco,Texas,<NA>,0.47,0.85,0.14,0.26
2455,2444,Burnout Legends,PSP,2013,Jul,Racing,Electronic Arts,USA,Thousand Oaks,California,<NA>,0.7,0.85,0.21,0.26
2456,2445,Wwe 2K15,PS3,2013,Aug,Sports,Take Two Interactive,USA,Freeport,Illinois,<NA>,0.36,0.85,0.11,0.26
2497,2486,Madden Nfl 07,PSP,2013,Jan,Sports,<NA>,USA,Lakewood,New Jersey,East,0.77,0.83,0.23,0.25
2504,2493,The Game Of Life,PS,2013,Aug,Misc,<NA>,USA,Santa Ana,California,West,0.46,0.83,0.14,0.25
2510,2499,Mlb Slugfest 2003,PS2,2013,Feb,Sports,<NA>,USA,Los Angeles,California,West,0.41,0.83,0.12,0.25
2557,2546,Final Fantasy Type0,PSP,2013,Jan,Role Playing,<NA>,USA,Seattle,Washington,West,0.0,0.81,0.00,0.24
2604,2593,Tales Of Destiny 2,PS2,2013,Dec,Role Playing,Namco Bandai Games,USA,Harlingen,Texas,<NA>,0.0,0.80,0.00,0.24
2605,2594,Capcoms Soccer Shootout,SNES,2013,Jan,Sports,Nintendo,USA,Louisville,Kentucky,<NA>,0.0,0.80,0.00,0.24
2606,2595,Sniper Ghost Warrior,PS3,2013,Feb,Shooter,City Interactive,USA,Louisville,Kentucky,<NA>,0.26,0.80,0.08,0.24
2607,2596,The Godfather Ii,X360,2013,Mar,Action,Electronic Arts,USA,Louisville,Kentucky,<NA>,0.47,0.79,0.14,0.24
2789,2778,Madden Nfl 11,WII,2015,May,Sports,<NA>,USA,Lawrence,Indiana,Central,0.7,0.74,0.21,0.22
2799,2788,Warioware Twisted,GBA,2010,Mar,Puzzle,<NA>,Australia,Melbourne,Victoria,Other,0.16,0.74,0.05,0.22
2842,2831,God Eater,PSP,2010,Oct,Action,<NA>,Australia,Sydney,New South Wales,West,0.0,0.72,0.00,0.22
3043,3032,Rift,PC,2011,Jul,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.44,0.67,0.13,0.20
3172,3161,Nicktoons Collection Game Boy Advance Video Vo...,GBA,2012,Apr,Misc,<NA>,Australia,Sydney,New South Wales,West,0.46,0.64,0.14,0.19
3179,3168,Spongebob Squarepants Game Boy Advance Video V...,GBA,2012,Nov,Misc,<NA>,Australia,Sydney,New South Wales,West,0.46,0.64,0.14,0.19
3481,3470,Nascar Dirt To Daytona,PS2,2012,Jan,Racing,<NA>,Australia,Sydney,New South Wales,West,0.28,0.58,0.08,0.17
3514,3503,Madden Nfl 2002,XB,2013,Oct,Sports,<NA>,Australia,Sydney,New South Wales,West,0.53,0.58,0.16,0.17
3715,3704,Two Worlds Ii,X360,2014,Jul,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.4,0.54,0.12,0.16
3779,3768,Spongebob Squarepants Game Boy Advance Video V...,GBA,2014,Nov,Misc,<NA>,Australia,Sydney,New South Wales,West,0.38,0.53,0.11,0.16
3979,3968,Chopper Command,2600,2014,Jul,Shooter,Activision,Australia,Sydney,New South Wales,<NA>,0.47,0.50,0.14,0.15
3980,3969,Activision Anthology,PS2,2014,Aug,Misc,Activision,Australia,Sydney,New South Wales,<NA>,0.25,0.50,0.08,0.15
3981,3970,Crash Mind Over Mutant,PS2,2014,Sep,Platform,Vivendi Games,Australia,Sydney,New South Wales,<NA>,0.25,0.50,0.08,0.15
3982,3971,Wwe 2K16,X360,2014,Oct,Sports,Take Two Interactive,Australia,Sydney,New South Wales,<NA>,0.27,0.50,0.08,0.15
3983,3972,Lego The Hobbit,X360,2014,Nov,Action,Warner Bros Interactive Entertainment,Australia,Sydney,New South Wales,<NA>,0.2,0.50,0.06,0.15
3984,3973,Babysitting Mama,WII,2014,Dec,Simulation,505 Games,Australia,Sydney,New South Wales,<NA>,0.34,0.50,0.10,0.15
3985,3974,Boogie,WII,2014,Jan,Misc,Electronic Arts,Australia,Sydney,New South Wales,<NA>,0.43,0.50,0.13,0.15
3986,3975,Theatrhythm Final Fantasy,3DS,2014,Feb,Misc,Square Enix,Australia,Sydney,New South Wales,<NA>,0.22,0.50,0.07,0.15
3987,3976,Bleach Soul Resurreccion,PS3,2014,Mar,Fighting,Nippon Ichi Software,Australia,Sydney,New South Wales,<NA>,0.27,0.50,0.08,0.15
3988,3977,Madden Nfl 07,WII,2014,Apr,Sports,Electronic Arts,Australia,Sydney,New South Wales,<NA>,0.46,0.50,0.14,0.15
3989,3978,Rugrats In Paris The Movie,N64,2014,May,Action,Thq,Australia,Sydney,New South Wales,<NA>,0.4,0.50,0.12,0.15
4134,4123,Two Worlds Ii,PS3,2014,Jun,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.26,0.48,0.08,0.14
4158,4147,Sonic The Hedgehog,PS3,2015,Jun,Platform,<NA>,Australia,Sydney,New South Wales,West,0.0,0.48,0.00,0.14
4539,4528,The Fairly Odd Parents Game Boy Advance Video ...,GBA,2015,Mar,Misc,<NA>,Australia,Sydney,New South Wales,West,0.31,0.43,0.09,0.13
4549,4538,Nhl Slapshot,WII,2015,Jan,Sports,<NA>,Australia,Sydney,New South Wales,West,0.4,0.43,0.12,0.13
4648,4637,The Fairly Odd Parents Game Boy Advance Video ...,GBA,2015,Apr,Misc,<NA>,Australia,Sydney,New South Wales,West,0.3,0.42,0.09,0.13
4696,4685,Tera,PC,2015,Apr,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.24,0.41,0.07,0.12
4810,4799,Nfl Gameday 2003,PS2,2016,Oct,Sports,<NA>,Australia,Sydney,New South Wales,West,0.2,0.40,0.06,0.12
4878,4867,Harvest Moon Save The Homeland,PS2,2016,Jun,Simulation,<NA>,Australia,Sydney,New South Wales,West,0.19,0.40,0.06,0.12
5184,5173,Bejeweled 3,DS,2016,Dec,Puzzle,<NA>,Australia,Sydney,New South Wales,West,0.32,0.36,0.10,0.11
5208,5197,Cubix Robots For Everyone Clash N Bash,GBA,2016,Dec,Action,<NA>,Australia,Sydney,New South Wales,West,0.26,0.36,0.08,0.11
5315,5304,Dragon Ball Z Budokai Tenkaichi 2 Jp Sales,WII,2016,Nov,Action,<NA>,Australia,Sydney,New South Wales,West,0.15,0.35,0.04,0.10
5631,5620,Final Fantasy Xi,PS2,2017,Mar,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.08,0.32,0.02,0.10
5638,5627,Singularity,X360,2017,Oct,Shooter,<NA>,Australia,Sydney,New South Wales,West,0.24,0.32,0.07,0.10
5660,5649,Cartoon Network Collection Game Boy Advance Vi...,GBA,2017,Aug,Misc,<NA>,Australia,Sydney,New South Wales,West,0.23,0.32,0.07,0.10
5682,5671,Allstar Baseball 2005,PS2,2017,Jun,Sports,<NA>,Australia,Sydney,New South Wales,West,0.16,0.32,0.05,0.10
5874,5863,The Dukes Of Hazzard Ii Daisy Dukes It Out,PS,2017,Jun,Racing,<NA>,Australia,Sydney,New South Wales,West,0.17,0.30,0.05,0.09

In [89]:
df[df['Publisher'].isnull()]

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
480,471,Wwe Smackdown Vs Raw 2006,PS2,2010,Mar,Fighting,<NA>,USA,New York City,New York,East,1.57,3.00,0.47,0.90
950,942,Gran Turismo Concept 2001 Tokyo,PS2,2011,May,Racing,<NA>,USA,Smyrna,Georgia,South,0.0,1.84,0.00,0.55
1313,1305,Triple Play 99,PS,2013,Aug,Sports,<NA>,USA,Appleton,Wisconsin,Central,0.81,1.46,0.24,0.44
1662,1651,Nascar Thunder 2003,PS2,2015,Jun,Racing,<NA>,USA,Woodland,California,West,0.6,1.22,0.18,0.37
1675,1664,Shrek Shrek 2 2In1 Gameboy Advance Video,GBA,2011,Jul,Misc,<NA>,USA,San Diego,California,West,0.87,1.21,0.26,0.36
2127,2116,Suikoden Iii,PS2,2012,Mar,Role Playing,<NA>,USA,Pasadena,Texas,Central,0.29,0.98,0.09,0.29
2186,2175,Wheel Of Fortune,PS2,2012,Feb,Misc,<NA>,USA,Newark,Delaware,East,0.47,0.95,0.14,0.28
2235,2224,Bentleys Hackpack,GBA,2012,Mar,Misc,<NA>,USA,New York City,New York,East,0.67,0.93,0.20,0.28
2249,2238,Teenage Mutant Ninja Turtles,GBA,2012,May,Action,<NA>,USA,Philadelphia,Pennsylvania,East,0.67,0.93,0.20,0.28
2299,2288,Namco Museum,XB,2012,Jul,Misc,<NA>,USA,Toledo,Ohio,East,0.77,0.91,0.23,0.27
2308,2297,Rhythm Heaven,WII,2012,Apr,Misc,<NA>,USA,Albuquerque,New Mexico,West,0.13,0.90,0.04,0.27
2341,2330,Blitz The League,PS2,2012,Jan,Sports,<NA>,USA,Seattle,Washington,West,0.74,0.89,0.22,0.27
2497,2486,Madden Nfl 07,PSP,2013,Jan,Sports,<NA>,USA,Lakewood,New Jersey,East,0.77,0.83,0.23,0.25
2504,2493,The Game Of Life,PS,2013,Aug,Misc,<NA>,USA,Santa Ana,California,West,0.46,0.83,0.14,0.25
2510,2499,Mlb Slugfest 2003,PS2,2013,Feb,Sports,<NA>,USA,Los Angeles,California,West,0.41,0.83,0.12,0.25
2557,2546,Final Fantasy Type0,PSP,2013,Jan,Role Playing,<NA>,USA,Seattle,Washington,West,0.0,0.81,0.00,0.24
2789,2778,Madden Nfl 11,WII,2015,May,Sports,<NA>,USA,Lawrence,Indiana,Central,0.7,0.74,0.21,0.22
2799,2788,Warioware Twisted,GBA,2010,Mar,Puzzle,<NA>,Australia,Melbourne,Victoria,Other,0.16,0.74,0.05,0.22
2842,2831,God Eater,PSP,2010,Oct,Action,<NA>,Australia,Sydney,New South Wales,West,0.0,0.72,0.00,0.22
3043,3032,Rift,PC,2011,Jul,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.44,0.67,0.13,0.20
3172,3161,Nicktoons Collection Game Boy Advance Video Vo...,GBA,2012,Apr,Misc,<NA>,Australia,Sydney,New South Wales,West,0.46,0.64,0.14,0.19
3179,3168,Spongebob Squarepants Game Boy Advance Video V...,GBA,2012,Nov,Misc,<NA>,Australia,Sydney,New South Wales,West,0.46,0.64,0.14,0.19
3481,3470,Nascar Dirt To Daytona,PS2,2012,Jan,Racing,<NA>,Australia,Sydney,New South Wales,West,0.28,0.58,0.08,0.17
3514,3503,Madden Nfl 2002,XB,2013,Oct,Sports,<NA>,Australia,Sydney,New South Wales,West,0.53,0.58,0.16,0.17
3715,3704,Two Worlds Ii,X360,2014,Jul,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.4,0.54,0.12,0.16
3779,3768,Spongebob Squarepants Game Boy Advance Video V...,GBA,2014,Nov,Misc,<NA>,Australia,Sydney,New South Wales,West,0.38,0.53,0.11,0.16
4134,4123,Two Worlds Ii,PS3,2014,Jun,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.26,0.48,0.08,0.14
4158,4147,Sonic The Hedgehog,PS3,2015,Jun,Platform,<NA>,Australia,Sydney,New South Wales,West,0.0,0.48,0.00,0.14
4539,4528,The Fairly Odd Parents Game Boy Advance Video ...,GBA,2015,Mar,Misc,<NA>,Australia,Sydney,New South Wales,West,0.31,0.43,0.09,0.13
4549,4538,Nhl Slapshot,WII,2015,Jan,Sports,<NA>,Australia,Sydney,New South Wales,West,0.4,0.43,0.12,0.13
4648,4637,The Fairly Odd Parents Game Boy Advance Video ...,GBA,2015,Apr,Misc,<NA>,Australia,Sydney,New South Wales,West,0.3,0.42,0.09,0.13
4696,4685,Tera,PC,2015,Apr,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.24,0.41,0.07,0.12
4810,4799,Nfl Gameday 2003,PS2,2016,Oct,Sports,<NA>,Australia,Sydney,New South Wales,West,0.2,0.40,0.06,0.12
4878,4867,Harvest Moon Save The Homeland,PS2,2016,Jun,Simulation,<NA>,Australia,Sydney,New South Wales,West,0.19,0.40,0.06,0.12
5184,5173,Bejeweled 3,DS,2016,Dec,Puzzle,<NA>,Australia,Sydney,New South Wales,West,0.32,0.36,0.10,0.11
5208,5197,Cubix Robots For Everyone Clash N Bash,GBA,2016,Dec,Action,<NA>,Australia,Sydney,New South Wales,West,0.26,0.36,0.08,0.11
5315,5304,Dragon Ball Z Budokai Tenkaichi 2 Jp Sales,WII,2016,Nov,Action,<NA>,Australia,Sydney,New South Wales,West,0.15,0.35,0.04,0.10
5631,5620,Final Fantasy Xi,PS2,2017,Mar,Role Playing,<NA>,Australia,Sydney,New South Wales,West,0.08,0.32,0.02,0.10
5638,5627,Singularity,X360,2017,Oct,Shooter,<NA>,Australia,Sydney,New South Wales,West,0.24,0.32,0.07,0.10
5660,5649,Cartoon Network Collection Game Boy Advance Vi...,GBA,2017,Aug,Misc,<NA>,Australia,Sydney,New South Wales,West,0.23,0.32,0.07,0.10
5682,5671,Allstar Baseball 2005,PS2,2017,Jun,Sports,<NA>,Australia,Sydney,New South Wales,West,0.16,0.32,0.05,0.10
5874,5863,The Dukes Of Hazzard Ii Daisy Dukes It Out,PS,2017,Jun,Racing,<NA>,Australia,Sydney,New South Wales,West,0.17,0.30,0.05,0.09

In [90]:
df[df['Region'].isna()]

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
13,10,Duck Hunt,NES,2010,Oct,Shooter,Nintendo,USA,Dallas,Texas,<NA>,26.93,28.31,8.08,8.49
38,35,Call Of Duty Black Ops Ii,PS3,2010,Nov,Shooter,Activision,USA,Stockton,California,<NA>,4.99,14.03,1.50,4.21
53,50,Pokemon Omega Rubypokemon Alpha Sapphire,3DS,2010,Feb,Role Playing,Nintendo,USA,New York City,New York,<NA>,4.23,11.33,1.27,3.40
84,78,Fifa 16,PS4,2010,Jun,Sports,Electronic Arts,USA,Carrollton,Texas,<NA>,1.11,8.49,0.33,2.55
126,120,Uncharted 2 Among Thieves,PS3,2010,Dec,Action,Sony Computer Entertainment,USA,Los Angeles,California,<NA>,3.27,6.73,0.98,2.02
210,204,Super Smash Bros For Wii U And 3Ds,WIIU,2010,Dec,Fighting,Nintendo,USA,New York City,New York,<NA>,2.59,5.02,0.78,1.51
225,219,Assassins Creed,PS3,2010,Mar,Adventure,Ubisoft,USA,Palm Coast,Florida,<NA>,1.91,4.83,0.57,1.45
243,237,The Last Of Us,PS4,2010,Sep,Action,Sony Computer Entertainment,USA,Lakeville,Minnesota,<NA>,1.78,4.55,0.53,1.36
2453,2442,Harry Potter And The Order Of The Phoenix,DS,2013,May,Action,Electronic Arts,USA,Philadelphia,Pennsylvania,<NA>,0.28,0.85,0.08,0.26
2454,2443,Rampage World Tour,PS,2013,Jun,Action,Gt Interactive,USA,Waco,Texas,<NA>,0.47,0.85,0.14,0.26
2455,2444,Burnout Legends,PSP,2013,Jul,Racing,Electronic Arts,USA,Thousand Oaks,California,<NA>,0.7,0.85,0.21,0.26
2456,2445,Wwe 2K15,PS3,2013,Aug,Sports,Take Two Interactive,USA,Freeport,Illinois,<NA>,0.36,0.85,0.11,0.26
2604,2593,Tales Of Destiny 2,PS2,2013,Dec,Role Playing,Namco Bandai Games,USA,Harlingen,Texas,<NA>,0.0,0.80,0.00,0.24
2605,2594,Capcoms Soccer Shootout,SNES,2013,Jan,Sports,Nintendo,USA,Louisville,Kentucky,<NA>,0.0,0.80,0.00,0.24
2606,2595,Sniper Ghost Warrior,PS3,2013,Feb,Shooter,City Interactive,USA,Louisville,Kentucky,<NA>,0.26,0.80,0.08,0.24
2607,2596,The Godfather Ii,X360,2013,Mar,Action,Electronic Arts,USA,Louisville,Kentucky,<NA>,0.47,0.79,0.14,0.24
3979,3968,Chopper Command,2600,2014,Jul,Shooter,Activision,Australia,Sydney,New South Wales,<NA>,0.47,0.50,0.14,0.15
3980,3969,Activision Anthology,PS2,2014,Aug,Misc,Activision,Australia,Sydney,New South Wales,<NA>,0.25,0.50,0.08,0.15
3981,3970,Crash Mind Over Mutant,PS2,2014,Sep,Platform,Vivendi Games,Australia,Sydney,New South Wales,<NA>,0.25,0.50,0.08,0.15
3982,3971,Wwe 2K16,X360,2014,Oct,Sports,Take Two Interactive,Australia,Sydney,New South Wales,<NA>,0.27,0.50,0.08,0.15
3983,3972,Lego The Hobbit,X360,2014,Nov,Action,Warner Bros Interactive Entertainment,Australia,Sydney,New South Wales,<NA>,0.2,0.50,0.06,0.15
3984,3973,Babysitting Mama,WII,2014,Dec,Simulation,505 Games,Australia,Sydney,New South Wales,<NA>,0.34,0.50,0.10,0.15
3985,3974,Boogie,WII,2014,Jan,Misc,Electronic Arts,Australia,Sydney,New South Wales,<NA>,0.43,0.50,0.13,0.15
3986,3975,Theatrhythm Final Fantasy,3DS,2014,Feb,Misc,Square Enix,Australia,Sydney,New South Wales,<NA>,0.22,0.50,0.07,0.15
3987,3976,Bleach Soul Resurreccion,PS3,2014,Mar,Fighting,Nippon Ichi Software,Australia,Sydney,New South Wales,<NA>,0.27,0.50,0.08,0.15
3988,3977,Madden Nfl 07,WII,2014,Apr,Sports,Electronic Arts,Australia,Sydney,New South Wales,<NA>,0.46,0.50,0.14,0.15
3989,3978,Rugrats In Paris The Movie,N64,2014,May,Action,Thq,Australia,Sydney,New South Wales,<NA>,0.4,0.50,0.12,0.15

In [91]:
pd.reset_option('display.max_rows')

# fillna()

In [92]:
# Publisher - 42 -> fillna with Unknown Publisher
# Region - 27 -> fillna with Unknown Region

In [93]:
# For Categories we dont change directly so convert them into string - after filling - back to same data type
cols=['Publisher','Region']
df[cols]=df[cols].astype('string')

df.fillna({
    'Publisher':'Unknown Publisher',
    'Region':'Unknown Region'
}, inplace=True)

df[cols]=df[cols].astype('category')

df.isna().sum()

Rank             0
Name             0
Platform         0
Year             0
Month            0
Genre            0
Publisher        0
Country          0
City             0
State            0
Region           0
NA_Sales         0
Global_Sales     0
NA_Profit        0
Global_Profit    0
dtype: int64

In [94]:
df.shape

(5893, 15)

In [95]:
df

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,NA_Sales,Global_Sales,NA_Profit,Global_Profit
0,1,Wii Sports,WII,2010,Jan,Sports,Nintendo,USA,Fairfield,California,West,41.49,82.74,12.45,24.82
1,2,Super Mario Bros,NES,2010,Feb,Platform,Nintendo,USA,Edmonds,Washington,West,29.08,40.24,8.72,12.07
2,3,Mario Kart Wii,WII,2010,Mar,Racing,Nintendo,USA,Louisville,Kentucky,South,15.85,35.82,4.76,10.75
3,4,Wii Sports Resort,WII,2010,Apr,Sports,Nintendo,USA,Round Rock,Texas,Central,15.75,33.00,4.72,9.90
4,5,Pokemon Redpokemon Blue,GB,2010,May,Role Playing,Nintendo,USA,Nashville,Tennessee,South,11.27,31.37,3.38,9.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5904,5890,Crazy Taxi Catch A Ride,GBA,2017,Sep,Racing,Thq,Australia,Sydney,New South Wales,West,0.21,0.30,0.06,0.09
5905,5891,Mysims Party,DS,2017,Oct,Simulation,Electronic Arts,Australia,Sydney,New South Wales,West,0.15,0.30,0.04,0.09
5906,5892,Harry Potter And The Order Of The Phoenix,X360,2017,Nov,Action,Electronic Arts,Australia,Sydney,New South Wales,West,0.24,0.30,0.07,0.09
5907,5893,Skylanders Superchargers,PS4,2017,Dec,Action,Activision,Australia,Sydney,New South Wales,West,0.17,0.30,0.05,0.09
5908,5894,Macross Digital Mission Vfx,PS,2017,Jan,Simulation,Namco Bandai Games,Australia,Sydney,New South Wales,West,0.0,0.30,0.00,0.09

In [96]:
df.rename(columns={'NA_Sales':'USA_Sales', 'NA_Profit':'USA_Profit'}, inplace=True)
df.head(10)

,Rank,Name,Platform,Year,Month,Genre,Publisher,Country,City,State,Region,USA_Sales,Global_Sales,USA_Profit,Global_Profit
0,1,Wii Sports,WII,2010,Jan,Sports,Nintendo,USA,Fairfield,California,West,41.49,82.74,12.45,24.82
1,2,Super Mario Bros,NES,2010,Feb,Platform,Nintendo,USA,Edmonds,Washington,West,29.08,40.24,8.72,12.07
2,3,Mario Kart Wii,WII,2010,Mar,Racing,Nintendo,USA,Louisville,Kentucky,South,15.85,35.82,4.76,10.75
3,4,Wii Sports Resort,WII,2010,Apr,Sports,Nintendo,USA,Round Rock,Texas,Central,15.75,33.00,4.72,9.90
4,5,Pokemon Redpokemon Blue,GB,2010,May,Role Playing,Nintendo,USA,Nashville,Tennessee,South,11.27,31.37,3.38,9.41
5,6,Tetris,GB,2010,Jun,Puzzle,Nintendo,USA,Newark,Ohio,East,23.2,30.26,6.96,9.08
6,7,New Super Mario Bros,DS,2010,Jul,Platform,Nintendo,USA,Fremont,Nebraska,Central,11.38,30.01,3.41,9.00
7,8,Wii Play,WII,2010,Aug,Misc,Nintendo,USA,Odessa,Texas,Central,14.03,29.02,4.21,8.71
8,9,New Super Mario Bros Wii,WII,2010,Sep,Platform,Nintendo,USA,Fairfield,Ohio,East,14.59,28.62,4.38,8.59
13,10,Duck Hunt,NES,2010,Oct,Shooter,Nintendo,USA,Dallas,Texas,Unknown Region,26.93,28.31,8.08,8.49

In [97]:
df.to_csv('CleanedVideoGameSaleData.csv', index=False)

In [98]:




# 1> I performed detailed data cleaning on the Video Game Sales dataset, starting with understanding its structure and 
# removing duplicate records.
    
# 2> I standardized the data by fixing extra spaces, correcting capitalization, and ensuring proper data types and date formats.
    
# 3> I handled missing values, validated categories, corrected spelling errors, and verified unique values for consistency.
    
# 4> Finally, I resolved logical errors and treated outliers to make the dataset accurate, reliable, and ready for analysis.